- LICENSE
> [MOB-XXXX] Add missing license

- LICENSE
> quick update of master with license

- README.md
> Readme update [1.2.5]

- Client/AppDelegate.swift
- Client/ViewController.swift
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/API/KarhooUIScreenRouting.swift
- KarhooUISDK/API/ScreenBuilders.swift
- KarhooUISDK/Builders/BookingRequestScreenBuilder.swift
- KarhooUISDK/Common/KarhooTextInputView/KarhooInputView.swift
- KarhooUISDK/Common/KarhooTextInputView/KarhooPhoneInputView/KarhooPhoneInputView.swift
- KarhooUISDK/Common/KarhooTextInputView/KarhooTextInputView.swift
- KarhooUISDK/Common/Layout/Constraints.swift
- KarhooUISDK/Screens/BookingRequestScreen/BookingRequestMVP.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDK/Screens/GuestBookingRequestScreen/GuestBookingRequestPresenter.swift
- KarhooUISDK/Screens/GuestBookingRequestScreen/GuestBookingRequestViewController.swift
- KarhooUISDK/Screens/GuestBookingRequestScreen/PassengerDetails/PassengerDetailsMVP.swift
- KarhooUISDK/Screens/GuestBookingRequestScreen/PassengerDetails/PassengerDetailsView.swift
[MOB-2734](https://karhoo.atlassian.net/browse/MOB-2734)
Part 1, 
- Move passenger details view into its own view (out of view controller)  
- Add BookingRequest screen component to routing layer
Next
- UI Clean ups in line with figma design
- File renaming
- Merge duplicate payment method views
> MOB-2734 Part 1

- KarhooUISDK/API/ScreenBuilders.swift
- KarhooUISDKTests/TestCases/Screens/BookingRequestScreen/MockBookingRequestView.swift
[MOB-XXXX](https://karhoo.atlassian.net/browse/MOB-2734)
- repaired failing tests
- added default implementation for Booking Request builder 
> MOB-2734 [fixes]

- KarhooUISDK/Common/TripDetailsView/TripDetailsViewModel.swift
- KarhooUISDKTests/Mocks/TestUtil.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/TripDetailsViewModelSpec.swift
[MOB-2891](https://karhoo.atlassian.net/browse/MOB-2891)
Check for nil meeting point when setting showMeetingPoint. Currently displays meeting point view with no text.
N/a
> MOB-2891 - Fix meeting point display bug

- KarhooUISDK/API/KarhooComponents.swift
- KarhooUISDK/Common/Layout/Constraints.swift
- KarhooUISDK/Screens/BookingScreen/BookingMVP.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/BookingScreen/QuoteCategoryBarMVP/KarhooQuoteCategoryBarView.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListPresenter.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListViewController.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteListMVP.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteListPanelLayout.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteSortMVP/KarhooQuoteSortView.swift
- KarhooUISDKTests/Mocks/Screen/BookingScreen/MockBookingView.swift
- KarhooUISDKTests/Mocks/Screen/BookingScreen/QuoteList/MockQuoteListView.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/KarhooBookingPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/QuoteList/KarhooQuoteListPresenterSpec.swift
[MOB-2733](https://karhoo.atlassian.net/browse/MOB-2733)
- Quote list component
> MOB-2733 [Quote List component]

- KarhooUISDK/Classes/Payment/NonceProvider/KarhooPaymentNonceProvider.swift
- KarhooUISDK/Common/AddressBarMVP/KarhooAddressBarView.swift
- KarhooUISDK/Common/Analytics.swift
- KarhooUISDK/Common/BordedLabel.swift
- KarhooUISDK/Common/CurrencyCodeConverter.swift
- KarhooUISDK/Extensions/KarhooSDKExtensions/UIView+Extensions.swift
- KarhooUISDK/Screens/BookingRequestScreen/KarhooBookingRequestPresenter.swift
- KarhooUISDK/Screens/BookingRequestScreen/KarhooBookingRequestViewController.swift
- KarhooUISDK/Screens/BookingScreen/AddressBar/BookingAddressBarPresenter.swift
- KarhooUISDK/Screens/BookingScreen/DeepLinkObjects/KarhooQuoteSorter.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListPresenter.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListViewController.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteViewModel.swift
- KarhooUISDK/Screens/CardDetails/KarhooPaymentPresenter.swift
- KarhooUISDK/Screens/GuestBookingRequestScreen/GuestBookingRequestPresenter.swift
- KarhooUISDK/Screens/GuestBookingRequestScreen/GuestBookingRequestViewController.swift
- KarhooUISDK/Screens/JourneyScreen/DestinationEta/KarhooDestinationEtaView.swift
- KarhooUISDK/Screens/JourneyScreen/JourneyDetailsMVP/JourneyActionsView/JourneyActionsView.swift
- KarhooUISDK/Screens/Rides/RidesList/RideCell/RideCell.swift
- KarhooUISDKTests/KarhooSDKService/Quote/MockQuoteService.swift
- KarhooUISDKTests/Mocks/Common/MockAddressBarView.swift
- KarhooUISDKTests/Mocks/Screen/BookingScreen/QuoteList/MockQuoteListView.swift
- KarhooUISDKTests/Mocks/TestUtil.swift
- KarhooUISDKTests/TestCases/Common/CurrencyCodeConverterSpec.swift
- KarhooUISDKTests/TestCases/Common/KarhooPaymentNonceProviderSpec.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/QuoteCellViewModelSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingRequestScreen/KarhooBookingRequestPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/GuestBookingRequestScreen/KarhooGuestBookingRequestPresenterSpec.swift
- Podfile
- Podfile.lock
[MOB-XXXX](https://karhoo.atlassian.net/browse/MOB-2866)
- Update to Quotes V2
- [] Bugfix 
> MOB-2866 [Quotes V2 UI]

- KarhooUISDK/Common/Layout/Constraints.swift
- KarhooUISDK/Screens/AddressScreen/AddressMapView/KarhooAddressDisplayView.swift
- KarhooUISDK/Screens/AddressScreen/AddressMapView/KarhooAddressMapView.swift
- KarhooUISDK/Screens/AddressScreen/AddressViewController.swift
Fix unsatisfied constraint log and search bar disappearing after selecting on map
- constraint changes
> [MOB-xxxx]fix address map view and constraint break

- .gitignore
- Client/AppDelegate.swift
- KarhooUISDK.xcodeproj/project.pbxproj
- README.md
[MOB-2899](https://karhoo.atlassian.net/browse/MOB-2899)
- add keys to gitignore
> MOB-2899 [add keys to gitignore]

- KarhooUISDK/Translations/fr.lproj/Localizable.strings
> MOB-2813/2

- Client/AppDelegate.swift
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Common/BaseSelectionView/BaseSelectionView.swift
- KarhooUISDK/Common/BaseStackView.swift
- KarhooUISDK/Common/RoundedLabel.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListPresenter.swift
- KarhooUISDK/Screens/PaymentView/KarhooAddCardView.swift
- KarhooUISDKTests/Mocks/Common/MockKarhooPaymentView.swift
- KarhooUISDKTests/Mocks/Service/MockPaymentService.swift
- KarhooUISDKTests/TestCases/Common/ConstraintSwitcher/ResizingSwitcherTests.swift
- KarhooUISDKTests/TestCases/Screens/GuestBookingRequestScreen/KarhooGuestBookingRequestPresenterSpec.swift
- Podfile
- Podfile.lock
- clean up some lint warnings
- Add Adyen to podspec
- Fix tests
> MOB-XXX [Clean up]

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
- Podfile
- Podfile.lock
Integrate initial drop in code. TODO (get public key)
> MOB-2728-2

- Client/AppDelegate.swift
- Client/Info.plist
- Client/ViewController.swift
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Classes/Payment/AddCard/CardRegistrationFlow.swift
- KarhooUISDK/Classes/Payment/AddCard/KarhooCardRegistrationFlow.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/PaymentView/KarhooPaymentPresenter.swift
- Podfile
- Podfile.lock
[MOB-2729](https://karhoo.atlassian.net/browse/MOB-2729)
- display adyen drop in or braintree drop in depending on org payment provider type
- todo - integrate /payments and /payment-details (network SDK refactor required) 
- [] Bugfix 
> MOB-2729 [Adyen Drop in showing]

- KarhooUISDK.podspec
- Podfile
FloatingPanel 2.0 introduced some breaking changes. Until we get around to updating our implementation, the fix is to cap at the last stable release.
> Cap FloatingPanel version

- Client/ViewController.swift
- KarhooUISDK/Common/NavigationBar/KarhooNavigationBarView.swift
- Podfile.lock
```
leftButton.touchAreaEdgeInsets = UIEdgeInsets(top: -10, left: -10, bottom: -10, right: -10)	
``` 
(No such method touchAreaEdgeInset on UIButton)
> MOB-XXX fix compile error / nav bar error

- Client/Info.plist
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK.xcodeproj/xcshareddata/xcschemes/KarhooUISDKTests.xcscheme
- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Classes/Payment/AddCard/PaymentFactory.swift
- Podfile
- Podfile.lock
- fastlane/Fastfile
[MOB-2730](https://karhoo.atlassian.net/browse/MOB-2730)
- 3DS 2.0 implemented 
- transaction id used to book trip
TODO
- Error handling
- Increase test coverage
> MOB-2730 [Successful adyen payment]

- Client/ViewController.swift
- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Classes/Payment/AddCard/AdyenResponseHandler.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestPresenter.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestViewController.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/PassengerDetails/PassengerDetailsMVP.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/PassengerDetails/PassengerDetailsView.swift
- KarhooUISDK/Screens/BookingScreen/SharedPassengerDetails.swift
- KarhooUISDK/Screens/PaymentView/KarhooPaymentPresenter.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/KarhooPaymentPresenterSpec.swift
- Podfile.lock
[MOB-2914](https://karhoo.atlassian.net/browse/MOB-2914)
- Be able to book with Adyen - as a user authenticated through token swap
> MOB-2914-token

- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Classes/Payment/AddCard/AdyenResponseHandler.swift
- KarhooUISDK/Error/KarhooUISDKError.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/PassengerDetails/PassengerDetailsView.swift
- KarhooUISDK/Screens/PaymentView/KarhooPaymentPresenter.swift
[MOB-2960](https://karhoo.atlassian.net/browse/MOB-2960)
- Display authorised card
- Handle card refusals (display refusal reason eg. "CVC declined") 
> MOB-2960 [Display card + handle refusals]

- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
[MOB-3058](https://karhoo.atlassian.net/browse/MOB-3058)
fixed allow3ds
> MOB-3058: hotfix

- KarhooUISDK.podspec
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteListPanelLayout.swift
- Podfile
- Podfile.lock
[MOB-3044](https://karhoo.atlassian.net/browse/MOB-3044)
Fix for FloatingPanel 2.0.1 pod
> [MOB-3044] FloatingPanel 2.0.1 fix

- KarhooUISDK/Screens/BookingRequestScreen/BookingRequest/KarhooBookingRequestPresenter.swift
- KarhooUISDKTests/TestCases/Screens/BookingRequestScreen/KarhooBookingRequestPresenterSpec.swift
- Podfile
- Podfile.lock
[MOB-3066](https://karhoo.atlassian.net/browse/MOB-3066)
Add the trip id to the Booking request for Adyen payment
N/a
> MOB-3066 - Add trip id to booking request

- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Classes/Payment/AddCard/AdyenResponseHandler.swift
- Podfile
- Podfile.lock
[MOB-3088](https://karhoo.atlassian.net/browse/MOB-3088)
Rename transaction_id to trip_id for Adyen payments request and payments-details response
> MOB-3088 - Rename Adyen payment transaction_id to trip_id

- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDKTests/Mocks/Service/MockTripService.swift
- KarhooUISDKTests/Mocks/TestUtil.swift
- Podfile.lock
[MOB-2993](https://karhoo.atlassian.net/browse/MOB-2993)
> [MOB-2993]: Retrieve the estimated cancellation fee

- .gitignore
- KarhooUISDK/Common/MailComposer/KarhooFeedbackMailComposer.swift
- KarhooUISDK/Common/UITexts.swift
- KarhooUISDK/Screens/SideMenu/SideMenuContent/MenuContentMVP.swift
- KarhooUISDK/Screens/SideMenu/SideMenuContent/MenuContentPresenter.swift
- KarhooUISDK/Screens/SideMenu/SideMenuContent/MenuContentViewController.swift
- KarhooUISDK/Screens/SideMenu/SideMenuContent/MenuContentViewController.xib
- KarhooUISDK/Screens/SideMenu/SideMenuHandler.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDKTests/Mocks/Routing/MockSideMenuHandler.swift
[MOB-3005](https://karhoo.atlassian.net/browse/MOB-3005)
Remove help section from the menu and update the email template for feedback and report trip issue 
> MOB-3005 Remove Help from menu and update email template

- KarhooUISDK/Screens/SideMenu/SideMenuContent/MenuContentViewController.xib
- Podfile.lock
[MOB-3073](https://karhoo.atlassian.net/browse/MOB-3073)
menu tests identifiers added
> [MOB-3073]: menu tests identifiers added

- KarhooUISDK/Screens/DatePickerScreen/View/DatePickerViewController.xib
[MOB-2272](https://karhoo.atlassian.net/browse/MOB-2272)
> [MOB-2272]: identifier added for UI tests

- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/PassengerDetails/PassengerDetailsView.swift
[MOB-3014](https://karhoo.atlassian.net/browse/MOB-3014)
get current locale added to passengerDetailsView for guest user booking
> [MOB-3014]: Use device locale for Guest bookings

- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestPresenter.swift
- KarhooUISDKTests/TestCases/Screens/GuestBookingRequestScreen/KarhooGuestBookingRequestPresenterSpec.swift
- KarhooUISDKTests/UnitTestSetup.swift
- Podfile
- Podfile.lock
[MOB-2925](https://karhoo.atlassian.net/browse/MOB-2925)
Use saved payment info for token exchange booking
> MOB-2925 - Use saved payment card for token exchange

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Podfile.lock
[MOB-3152](https://karhoo.atlassian.net/browse/MOB-3152)
> Update Marketing version for 1.4.0

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Podfile.lock
[MOB-3152](https://karhoo.atlassian.net/browse/MOB-3152)
> Update Marketing version for 1.4.0 (#68)

- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListPresenter.swift
- Podfile
- Podfile.lock
[MOB-2976](https://karhoo.atlassian.net/browse/MOB-2976)
Should no longer refresh when quote status is completed. Instead, it will be waiting for a timer based on quote validity.
> [MOB-2976] Quote polling fix

- KarhooUISDK/Common/UITexts.swift
- KarhooUISDK/Screens/BookingScreen/BookingMVP.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/BookingScreen/TripAllocationMVP/KarhooTripAllocationPresenter.swift
- KarhooUISDK/Screens/BookingScreen/TripAllocationMVP/KarhooTripAllocationView.swift
- KarhooUISDK/Screens/BookingScreen/TripAllocationMVP/TripAllocationMVP.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDKTests/Mocks/Screen/BookingScreen/TripAllocation/MockTripAllocationView.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/KarhooBookingPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/TripAllocation/KarhooTripAllocationPresenterSpec.swift
- Podfile.lock
[MOB-2948](https://karhoo.atlassian.net/browse/MOB-2948)
Display am alert that allows the user to transition to the Ride Details screen when the is a delay allocation a driver
> MOB-2949 - Driver allocation delay alert

- KarhooUISDK/Common/KarhooTextField/KarhooTextField.xib
- KarhooUISDK/Common/MapMVP/AppleMapKit/KarhooMKMapView.swift
- Podfile.lock
[MOB-3148](https://karhoo.atlassian.net/browse/MOB-3148)
identifier added
> [MOB-3148]: identifier added

- KarhooUISDK/Classes/Payment/AddCard/BraintreeCardRegistrationFlow.swift
- KarhooUISDK/Classes/Payment/NonceProvider/BraintreePaymentNonceProvider.swift
- KarhooUISDK/Classes/Payment/NonceProvider/PaymentNonceProvider.swift
- KarhooUISDK/Routing/BaseViewController.swift
- KarhooUISDK/Screens/BookingRequestScreen/BookingRequest/KarhooBookingRequestPresenter.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestPresenter.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDK/Screens/DatePickerScreen/KarhooDatePickerPresenter.swift
- KarhooUISDK/Screens/PaymentView/KarhooPaymentPresenter.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/KarhooRideDetailsPresenter.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/RideDetailsViewController.swift
- KarhooUISDK/Screens/TripScreen/KarhooTripPresenter.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDKTests/Mocks/Common/MockBaseViewController.swift
- KarhooUISDKTests/TestCases/Common/BaseViewControllerSpec.swift
- KarhooUISDKTests/TestCases/Routing/KarhooCardRegistrationFlowSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingRequestScreen/MockBookingRequestView.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/TripAllocation/KarhooTripAllocationPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/GuestBookingRequestScreen/KarhooGuestBookingRequestPresenterSpec.swift
[MOB-3171](https://karhoo.atlassian.net/browse/MOB-3171)
Append KarhooError to the showAlert 
> Mob 3171 remove unused strings

- KarhooUISDK/Common/KarhooTextInputView/KarhooTextInputView.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestViewController.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/PassengerDetails/PassengerDetailsMVP.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/PassengerDetails/PassengerDetailsView.swift
[MOB-3141](https://karhoo.atlassian.net/browse/MOB-XXXX)
Prefill passenger details for token exchange
Update KarhooTextInputView to be able to handle set text values
> Prefill passenger details for token exchange

- KarhooUISDK/Classes/CancelRideBehaviour.swift
- KarhooUISDK/Common/UITexts.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/KarhooRideDetailsPresenter.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/RideDetailsViewController.swift
- KarhooUISDK/Screens/TripScreen/KarhooTripPresenter.swift
- KarhooUISDK/Screens/TripScreen/KarhooTripViewController.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDKTests/Mocks/Classes/MockCancelRideBehaviour.swift
- KarhooUISDKTests/Mocks/TestUtil.swift
- KarhooUISDKTests/TestCases/Common/CancelRideBehaviourSpec.swift
- KarhooUISDKTests/TestCases/Screens/Rides/KarhooRideDetailsPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/TripScreen/TripDetails/KarhooTripPresenterSpec.swift
- Podfile.lock
[MOB-3144](https://karhoo.atlassian.net/browse/MOB-3144)
Display the cancellation fee to the user and the option to accept or decline the cancellation.
> MOB-3144 - Display cancellation fee on Trip and Ride Details screens

- KarhooUISDK/Classes/CancelRideBehaviour.swift
- KarhooUISDKTests/TestCases/Common/CancelRideBehaviourSpec.swift
- Podfile
- Podfile.lock
[MOB-3144](https://karhoo.atlassian.net/browse/MOB-3144)
Updated to use fee with decimal value
> MOB-3144 - Add decimal formatting to currency display

- KarhooUISDK/Screens/Rides/RidesList/RideDetails/KarhooRideDetailsPresenter.swift
- KarhooUISDKTests/TestCases/Screens/Rides/KarhooRideDetailsPresenterSpec.swift
- Podfile.lock
[MOB-3197](https://karhoo.atlassian.net/browse/MOB-3197)
Take the user back to the Rides screen when the OK button is pressed on the successful cancellation alert
N/a
> MOB-3197 - Take user to Rides screen when OK is pressed on the successful cancellation alert on the Ride Details screen

- KarhooUISDK/Common/Layout/KarhooColors.swift
- KarhooUISDK/Common/UITexts.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteView.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteViewModel.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/KarhooRideDetailsPresenter.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDKTests/Mocks/TestUtil.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/QuoteCellViewModelSpec.swift
- KarhooUISDKTests/TestCases/Screens/Rides/KarhooRideDetailsPresenterSpec.swift
- Podfile.lock
[MOB-3193](https://karhoo.atlassian.net/browse/MOB-3193)
Display free cancellation minutes if there are any
> MOB-3193 - Cancellation SLA

- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
[MOB-3175](https://karhoo.atlassian.net/browse/MOB-3175)
Remove Suffix parameter from Adyen payments method
> Remove suffix url parameter from adyen

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Classes/Payment/AddCard/AdyenResponseHandler.swift
- KarhooUISDK/Classes/Payment/ThreeDSecure/AdyenThreeDSecureUtils.swift
- KarhooUISDK/Classes/Payment/ThreeDSecure/ThreeDSecureProvider.swift
- KarhooUISDK/Error/KarhooUISDKError.swift
- KarhooUISDK/Screens/BookingRequestScreen/BookingRequest/KarhooBookingRequestPresenter.swift
- Podfile
- Podfile.lock
[MOB-3203](https://karhoo.atlassian.net/browse/MOB-3203)
Force Adyen 3DS
> Force Adyen 3ds

- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Classes/Payment/AddCard/BraintreeCardRegistrationFlow.swift
- KarhooUISDK/Classes/Payment/AddCard/CardRegistrationFlow.swift
- KarhooUISDK/Classes/Payment/NonceProvider/AdyenPaymentNonceProvider.swift
- KarhooUISDK/Classes/Payment/NonceProvider/BraintreePaymentNonceProvider.swift
- KarhooUISDK/Screens/PaymentView/KarhooPaymentPresenter.swift
- KarhooUISDKTests/Mocks/Routing/MockCardRegistrationFlow.swift
- KarhooUISDKTests/Mocks/Service/MockPaymentService.swift
- KarhooUISDKTests/TestCases/Routing/AdyenCardRegistrationFlowSpec.swift
- KarhooUISDKTests/TestCases/Routing/KarhooCardRegistrationFlowSpec.swift
- Podfile.lock
[MOB-3205](https://karhoo.atlassian.net/browse/MOB-3205)
Add SupplyPartnerId to the AdyenPayments request
> Add SupplyPartnerId to the AdyenPayments request

- KarhooUISDK/Screens/PaymentView/KarhooPaymentPresenter.swift
- KarhooUISDKTests/Mocks/TestUtil.swift
- Podfile.lock
[MOB-3205](https://karhoo.atlassian.net/browse/MOB-3205)
update quote model use fleet
> Mob 3205 update quote model use fleet

- Client/AppDelegate.swift
- Client/Info.plist
- Client/ViewController.swift
[MOB-3205](https://karhoo.atlassian.net/browse/MOB-3205)
Handle 3DS callback in Client app
> Handle 3DS callback in Client app

- KarhooUISDK/Common/VehicleCapacityView/VehicleCapacityView.swift
- KarhooUISDK/Screens/BookingRequestScreen/BookingRequest/SupplierView/SupplierView.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormCheckoutHeaderView.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteView.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteViewModel.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/QuoteCellViewModelSpec.swift
[MOB-3194](https://karhoo.atlassian.net/browse/MOB-3194)
This notification was already displayed in the list of quotes received from the API. However, now we display the same message in the screens which confirm the booking of a selected, cancellable quote.
> When possible, show cancellable notification in the booking confirmation screens.

- KarhooUISDK/Screens/Rides/RidesList/RideCell/RideCell.swift
- KarhooUISDK/Screens/Rides/RidesList/RideCell/RideCellViewModel.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/TripMetaData/KarhooTripMetaDataView.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/TripMetaData/TripMetaDataViewModel.swift
- KarhooUISDKTests/Mocks/TestUtil.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/RideCellViewModelSpec.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/TripMetaDataViewModelSpec.swift
[MOB-3179](https://karhoo.atlassian.net/browse/MOB-3179)
> Show free cancellation info in the ride list and details screens

- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteView.swift
* On small devices
[MOB-3220](https://karhoo.atlassian.net/browse/MOB-3220)
> Do not cut off price information in the quote list

- KarhooUISDK/Common/UITexts.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteViewModel.swift
- KarhooUISDK/Screens/Rides/RidesList/RideCell/RideCellViewModel.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/TripMetaData/TripMetaDataViewModel.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDKTests/TestCases/Common/ViewModel/QuoteCellViewModelSpec.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/RideCellViewModelSpec.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/TripMetaDataViewModelSpec.swift
[MOB-3223](https://karhoo.atlassian.net/browse/MOB-3223)
> Add free cancellation message when available before driver en route

- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteViewModel.swift
- KarhooUISDK/Screens/Rides/RidesList/RideCell/RideCellViewModel.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/TripMetaData/TripMetaDataViewModel.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/QuoteCellViewModelSpec.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/RideCellViewModelSpec.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/TripMetaDataViewModelSpec.swift
- Podfile.lock
[MOB-3223](https://karhoo.atlassian.net/browse/MOB-3223)
> Refactor to use enum cancellation types.

- KarhooUISDK/Common/AddressBarMVP/KarhooAddressBarView.swift
[MOB-2778](https://karhoo.atlassian.net/browse/MOB-2778)
> fix and refactoring icon size

- KarhooUISDKTests/TestCases/Screens/BookingScreen/KarhooBookingViewController+BuilderSpec.swift
[MOB-3185](https://karhoo.atlassian.net/browse/MOB-3185)
> [MOB-3185] Fix test

- KarhooUISDK/Classes/CancelRideBehaviour.swift
- KarhooUISDK/Common/CurrencyCodeConverter.swift
- KarhooUISDK/Extensions/KarhooSDKExtensions/FareExt.swift
- KarhooUISDK/Extensions/KarhooSDKExtensions/TripExt.swift
- KarhooUISDKTests/Mocks/TestUtil.swift
- KarhooUISDKTests/TestCases/Common/CancelRideBehaviourSpec.swift
- KarhooUISDKTests/TestCases/Common/CurrencyCodeConverterSpec.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/QuoteCellViewModelSpec.swift
- KarhooUISDKTests/TestCases/Extension/TripExtSpec.swift
[MOB-3256](https://karhoo.atlassian.net/browse/MOB-3256)
> changed price display rules

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Podfile.lock
[MOB-3216](https://karhoo.atlassian.net/browse/MOB-3216)
> [MOB-3216] Release 1.5.0

- KarhooUISDK.podspec
- Podfile
[MOB-3275](https://karhoo.atlassian.net/browse/MOB-3275)
Right now, if trying to update, Braintree drop-in will install version 9, which is not supported. This solves the problem.
> Make Braintree versions more specific.

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Podfile.lock
Release 1.5.1 for side menu update with lite burger menu
> [MOB-XXXX] Release 1.5.1

- KarhooUISDK/Common/UITexts.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDK/Screens/BookingScreen/TripAllocationMVP/KarhooTripAllocationPresenter.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDKTests/Mocks/Common/MockBaseViewController.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/KarhooBookingPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/TripAllocation/KarhooTripAllocationPresenterSpec.swift
- Podfile.lock
[MOB-3289](https://karhoo.atlassian.net/browse/MOB-3289)
> Redirect to trip tracking url only when user confirms the action after an alert action

- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormCheckoutHeaderView.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteView.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteViewModel.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/QuoteCellViewModelSpec.swift
- Podfile.lock
Also made this change for token exchange experiences.
[MOB-3292](https://karhoo.atlassian.net/browse/MOB-3292)
> Display correct schedule for guest prebooked rides in the booking request view

- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListPresenter.swift
- KarhooUISDKTests/Mocks/Screen/BookingScreen/Domain/MockQuoteSorter.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/QuoteList/KarhooQuoteListPresenterSpec.swift
- Podfile.lock
[MOB-3357](https://karhoo.atlassian.net/browse/MOB-3357)
Sort quotes by price when the user choses to prebook the ride.
> Sort quotes by price when the user choses to prebook the ride.

- KarhooUISDK/Screens/AddressScreen/AddressPresenter.swift
- KarhooUISDKTests/TestCases/Screens/AddressScreen/KarhooAddressPresenterSpec.swift
[MOB-3245](https://karhoo.atlassian.net/browse/MOB-3245)
> Reverse geocode only once when double tapping on current location

- KarhooUISDK/API/KarhooUISDKConfiguration.swift
- KarhooUISDK/Builders/BookingRequestScreenBuilder.swift
- KarhooUISDK/Screens/BookingRequestScreen/BookingRequest/KarhooBookingRequestPresenter.swift
- KarhooUISDK/Screens/BookingRequestScreen/BookingRequest/KarhooBookingRequestViewController.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestPresenter.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestViewController.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDKTests/Mocks/Builders/MockBookingRequestScreenBuilder.swift
- KarhooUISDKTests/TestCases/Screens/BookingRequestScreen/KarhooBookingRequestPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/GuestBookingRequestScreen/KarhooGuestBookingRequestPresenterSpec.swift
[MOB-3373](https://karhoo.atlassian.net/browse/MOB-3373)
> Add metadata dictionary to Booking Request view to be sent to booking api

- KarhooUISDK/Common/Domain/KarhooBookingStatus.swift
- KarhooUISDK/Screens/AddressScreen/AddressMVP.swift
- KarhooUISDK/Screens/AddressScreen/AddressPresenter.swift
- KarhooUISDK/Screens/AddressScreen/AddressViewController.swift
- KarhooUISDK/Screens/BookingScreen/Map/EmptyMapBookingStrategy.swift
- KarhooUISDK/Screens/BookingScreen/Map/PickupOnlyStrategy.swift
- KarhooUISDKTests/Mocks/Screen/Address/MockAddressView.swift
- KarhooUISDKTests/TestCases/Screens/AddressScreen/KarhooAddressPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/Map/EmptyBookingMapStrategySpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/Map/PickupOnlyStrategySpec.swift
https://karhoo.atlassian.net/browse/MOB-3333
MOB-3333 [Config & Prep] Set the default map zoom
> MOB-3333 [Config & Prep] Set the default map zoom

- KarhooUISDK/Common/UITexts.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteViewModel.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDKTests/TestCases/Common/ViewModel/QuoteCellViewModelSpec.swift
[MOB-3383](https://karhoo.atlassian.net/browse/MOB-3383)
Display a different free cancellation message when the booking is ASAP
> Modify cancellation period displayed on the quote for ASAP rides

- KarhooUISDK/Common/UITexts.swift
- KarhooUISDK/Common/URLOpener.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteCell/QuoteViewModel.swift
- KarhooUISDK/Screens/Rides/RidesList/RideCell/RideCellViewModel.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/TripMetaData/TripMetaDataViewModel.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- Podfile
- Podfile.lock
[MOB-3383](https://karhoo.atlassian.net/browse/MOB-3383)
Display the correct message in the rides screen
> Display the correct message in the rides screen

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
[MOB-3387](https://karhoo.atlassian.net/browse/MOB-3387)
Bump version number, use NSDK 1.5.0
> Release 1.6.0 (develop)

- KarhooUISDK/Screens/Rides/RidesList/RideCell/RideCell.swift
- Podfile.lock
[MOB-3387](https://karhoo.atlassian.net/browse/MOB-3387)
> Release 1.6.0 hotfix (master)

- KarhooUISDK/Screens/Rides/RidesList/RideCell/RideCell.swift
- Podfile.lock
[MOB-3387](https://karhoo.atlassian.net/browse/MOB-3387)
Hotfix for rides screen navigation to track driver
> Release 1.6.0 hotfix (develop)

- README.md
> Update SDK version in the readme

- KarhooUISDK/Common/UITexts.swift
- KarhooUISDK/Common/URLOpener.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
[MOB-3439](https://karhoo.atlassian.net/browse/MOB-3439)
> [MOB-3439] Custom tracking links

- KarhooUISDK/Common/KarhooTextInputView/KarhooTextInputView.swift
- KarhooUISDK/Screens/BookingRequestScreen/BookingRequest/BookingButtonMVP/KarhooBookingButtonView.swift
- KarhooUISDK/Screens/SideMenu/SideMenuContent/MenuContentViewController.swift
- KarhooUISDK/Screens/SideMenu/SideMenuContent/MenuContentViewController.xib
[MOB-3384](https://karhoo.atlassian.net/browse/MOB-3384)
> MOB-3384 Fix/passenger title black

- KarhooUISDK/Screens/Rides/RidesViewController.swift
[MOB-3384](https://karhoo.atlassian.net/browse/MOB-3384)
> MOB-3384 set text color to accent on upcoming tab label in rides screen

- Podfile
- Podfile.lock
[MOB-3450](https://karhoo.atlassian.net/browse/MOB-3450)
> Mob 3450 use new sdk 1 5 1 version

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Podfile.lock
- README.md
[MOB-3450](https://karhoo.atlassian.net/browse/MOB-3450)
> updated to 1.6.1-rc1

- KarhooUISDK/Screens/Rides/RidesList/RideDetails/TripMetaData/KarhooTripMetaDataView.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/TripMetaData/TripMetaDataViewModel.swift
[MOB-3481](https://karhoo.atlassian.net/browse/MOB-3481)
> MOB-3481: Remove the ratingview from the rides details screen

- KarhooUISDK/Screens/AddressScreen/AddressMapView/KarhooAddressDisplayView.swift
- KarhooUISDK/Screens/AddressScreen/AddressMapView/KarhooAddressMapView.swift
[MOB-3477](https://karhoo.atlassian.net/browse/MOB-3477)
> MOB-3477: Update Constraint for address display view

- Client/ViewController.swift
- KarhooUISDK/Screens/AddressScreen/AddressMapView/KarhooAddressMapPresenter.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/BookingScreen/Map/BookingMapStrategy.swift
- KarhooUISDK/Screens/BookingScreen/Map/DestinationSetStrategy.swift
- KarhooUISDK/Screens/BookingScreen/Map/EmptyMapBookingStrategy.swift
- KarhooUISDK/Screens/BookingScreen/Map/KarhooBookingMapPresenter.swift
- KarhooUISDK/Screens/BookingScreen/Map/PickupOnlyStrategy.swift
- KarhooUISDKTests/Mocks/Screen/BookingScreen/Map/MockBookingMapStrategy.swift
[MOB-3478](https://karhoo.atlassian.net/browse/MOB-3478)
> MOB-3478 Apply reverse geolocate flag on the map strategies

- KarhooUISDK.podspec
- KarhooUISDK/Classes/Payment/AddCard/PaymentFactory.swift
- Podfile
- Podfile.lock
[MOB-3514](https://karhoo.atlassian.net/browse/MOB-3514)
Update Adyen to 3.7.0
> MOB-3514 Release 1.6.3 (master)

- KarhooUISDK.podspec
- KarhooUISDK/Classes/Payment/AddCard/PaymentFactory.swift
- Podfile
- Podfile.lock
[MOB-3514](https://karhoo.atlassian.net/browse/MOB-3514)
Update Adyen SDK 3.7.0
> MOB-3514: Release 1.6.3 (develop)

- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/CheckoutViews/RideInfoView.swift
[MOB-3405](https://karhoo.atlassian.net/browse/MOB-3405)
> MOB-3405 make label to be button instead

- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/CheckoutViews/PassengerDetailsPaymentView.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestViewController.swift
[MOB-3430](https://karhoo.atlassian.net/browse/MOB-3430)
> MOB-3430 inject quote into PaymentView

- KarhooUISDK.xcodeproj/project.pbxproj
[MOB-3516](https://karhoo.atlassian.net/browse/MOB-3516)
> MOB-3516 update bundle id

- KarhooUISDK/Common/KarhooTextInputView/KarhooInputView.swift
- KarhooUISDK/Common/KarhooTextInputView/KarhooPhoneInputView/KarhooPhoneInputView.swift
- KarhooUISDK/Common/UITexts.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/PassengerDetails/PassengerDetailsViewController.swift
[MOB-3540](https://karhoo.atlassian.net/browse/MOB-3540)
> MOB-3540 temp PR to unblock tickets 3396 and 3428

- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestPresenter.swift
[MOB-3428](https://karhoo.atlassian.net/browse/MOB-3428)
> MOB-3428 fix adyen nonce retrieval

- KarhooUISDK/Screens/BookingRequestScreen/BookingRequestMVP.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestPresenter.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestViewController.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/PassengerDetails/PassengerDetailsViewController.swift
- KarhooUISDK/Utils.swift
[MOB-3540](https://karhoo.atlassian.net/browse/MOB-3540)
> Mob 3540 send correct passenger details

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Common/KarhooTextInputView/KarhooPhoneInputView.swift
- KarhooUISDK/Common/KarhooTextInputView/KarhooTextInputView.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestViewController+Extensions.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/PassengerDetails/PassengerDetailsViewController.swift
- KarhooUISDKTests/TestCases/Screens/PassengerDetails/MockPassengerDetailsViewController.swift
- KarhooUISDKTests/TestCases/Screens/PassengerDetails/PassengerDetailsPresenterSpec.swift
[MOB-3395](https://karhoo.atlassian.net/browse/MOB-3395)
> MOB-3395 - fix done button in the add passenger page

- KarhooUISDK/Screens/BookingRequestScreen/BookingRequestMVP.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestPresenter.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestViewController.swift
- KarhooUISDKTests/TestCases/Screens/BookingRequestScreen/MockBookingRequestView.swift
[MOB-3532](https://karhoo.atlassian.net/browse/MOB-3532)
> MOB-3532 add flag for showing retry alert

- KarhooUISDK/Common/KarhooTextInputView/KarhooPhoneInputView.swift
- KarhooUISDK/Common/KarhooTextInputView/KarhooTextInputView.swift
[MOB-3414](https://karhoo.atlassian.net/browse/MOB-3414)
> MOB-3414 add validation and error handling for empty field

- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestPresenter.swift
[MOB-3547](https://karhoo.atlassian.net/browse/MOB-3547)
> MOB-3547 - fix quote summary screen disappearing

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Common/Alert/AlertHandler.swift
- KarhooUISDK/Extensions/UIViewController+Extensions.swift
- KarhooUISDK/Routing/BaseViewController.swift
- KarhooUISDK/Screens/AddressScreen/AddressViewController.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/FormBookingRequestViewController.swift
- KarhooUISDK/Screens/BookingRequestScreen/FormBookingRequestScreen/PassengerDetails/PassengerDetailsViewController.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListViewController.swift
- KarhooUISDK/Screens/CountryCodeSelectionScreen/CountryCodeSelectionViewController.swift
- KarhooUISDK/Screens/DatePickerScreen/View/DatePickerViewController.swift
- KarhooUISDK/Screens/FlightDetailsScreen/View/FlightDetailsViewController.swift
- KarhooUISDK/Screens/PopupDialog/PopupDialogViewController.swift
- KarhooUISDK/Screens/PrebookConfirmationScreen/KarhooPrebookConfirmationViewController.swift
- KarhooUISDK/Screens/Rides/RidesList/RideDetails/RideDetailsViewController.swift
- KarhooUISDK/Screens/Rides/RidesList/RidesListViewController.swift
- KarhooUISDK/Screens/Rides/RidesViewController.swift
- KarhooUISDK/Screens/SideMenu/SideMenuContent/MenuContentViewController.swift
- KarhooUISDK/Screens/SideMenu/SideMenuViewController.swift
- KarhooUISDK/Screens/TripFeedbackScreen/KarhooTripFeedbackViewController.swift
- KarhooUISDK/Screens/TripScreen/KarhooTripViewController.swift
- KarhooUISDK/Screens/TripSummaryScreen/TripSummaryViewController.swift
- KarhooUISDK/Screens/UINavigation.swift
- KarhooUISDK/Utils.swift
[MOB-3490](https://karhoo.atlassian.net/browse/MOB-3490)
- [] New feature 
> MOB-3490 - force light mode

- KarhooUISDK/Classes/Payment/AddCard/AdyenCardRegistrationFlow.swift
- Podfile.lock
[MOB-3451](https://karhoo.atlassian.net/browse/MOB-3451)
> [MOB-3451] Adyen dropin to use secondary color

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Podfile.lock
- README.md
[MOB-3635](https://karhoo.atlassian.net/browse/MOB-3635)
> MOB-3635: release 1.7.0

- KarhooUISDK/Screens/CheckoutScreen/Components/AddPassengerDetailsView/KarhooAddPassengerDetailsView.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/AddPaymentView/KarhooAddPaymentView.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/LoyaltyView/KarhooLoyaltyView.swift
[MOB-3654](https://karhoo.atlassian.net/browse/MOB-3654)
> Mob 3654 feedback

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Models/LoyaltyViewDataModel.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewController.swift
- KarhooUISDK/UIComponents/LoyaltyView/KarhooLoyaltyPresenter.swift
- KarhooUISDK/UIComponents/LoyaltyView/KarhooLoyaltyView.swift
- KarhooUISDK/UIComponents/LoyaltyView/KarhooLoyaltyViewMVP.swift
- KarhooUISDK/ViewModels/LoyaltyViewModel.swift
- KarhooUISDK/Workers/Formatters/CurrencyCodeConverter.swift
- KarhooUISDKTests/Mocks/Screen/Loyalty/MockLoyaltyView.swift
- KarhooUISDKTests/TestCases/Screens/Loyalty/KarhooLoyaltyPresenterSpec.swift
add call to getLoyaltyEarn, refactor LoyaltyViewRequest to LoyaltyViewDataModel
[MOB-3657](https://karhoo.atlassian.net/browse/MOB-3657)
> MOB-3657 show earned points logic

- KarhooUISDK/UIComponents/LoyaltyView/KarhooLoyaltyPresenter.swift
- KarhooUISDK/Workers/Formatters/CurrencyCodeConverter.swift
[MOB-3684](https://karhoo.atlassian.net/browse/MOB-3684)
> MOB-3684 show burned points

- Client/ViewController.swift
> add separate scenario buttons for loyalty testing

- KarhooUISDK/UIComponents/LoyaltyView/KarhooLoyaltyPresenter.swift
[MOB-3650](https://karhoo.atlassian.net/browse/MOB-3650)
> MOB-3650 call loyalty pre-auth in earn mode

- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
[MOB-3802](https://karhoo.atlassian.net/browse/MOB-3802)
> MOB-3802 align all translations with the ones in phrase

- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListPresenter.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListViewController.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteListMVP.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
[MOB-3787](https://karhoo.atlassian.net/browse/MOB-3787)
> MOB-3787 - "Taxes and fees included" text added to Quote List

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
- README.md
[MOB-3749](https://karhoo.atlassian.net/browse/MOB-3749)
> MOB-3749: Release 1.7.1 [develop]

- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewController.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/BookingButton/KarhooBookingButtonView.swift
- KarhooUISDK/Screens/Rides/RidesViewController.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
https://user-images.githubusercontent.com/97090287/149005089-b5310a33-c324-4328-a667-cd1fbf552150.mp4
> MOB-3617 different button wording on checkout and rides list

- KarhooUISDK/CommonUI/Views/KarhooTextInputView/KarhooTextInputView.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/AddPassengerDetailsView/KarhooAddPassengerDetailsView.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/AddPaymentView/KarhooAddPaymentView.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/BookingButton/KarhooBookingButtonView.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/CheckoutViews/KarhooAddPassengerDetailsAndPaymentView.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/CheckoutViews/KarhooCheckoutHeaderView.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/CheckoutViews/KarhooLearnMoreButton.swift
[MOB-3722](https://karhoo.atlassian.net/browse/MOB-3722)
> MOB-3722 Accessibility improvements on Checkout

- KarhooUISDK/CommonUI/UIConstants.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListViewController.swift
[MOB-3816](https://karhoo.atlassian.net/browse/MOB-3816)
Reduce the hight from 55 to 30
> Reduce legal tax height in the qoute list

- KarhooUISDK/CommonUI/Buttons/CloseBarButton.swift
- KarhooUISDK/CommonUI/TripDetailsView/TripDetailsView.swift
- KarhooUISDK/CommonUI/TripDetailsView/TripDetailsViewModel.swift
- KarhooUISDK/CommonUI/Views/MetaDataView.swift
- KarhooUISDK/CommonUI/Views/StackButtonView/KarhooStackButtonView.swift
- KarhooUISDK/Screens/Rides/RidesList/RidesListViewController.swift
- KarhooUISDK/Screens/Rides/RidesViewController.swift
- KarhooUISDK/Screens/Rides/UIPageControl/RidesViewController.xib
- KarhooUISDK/Workers/Formatters/KarhooDateFormatter.swift
- KarhooUISDKTests/Mocks/Common/MockDataFormatterType.swift
[MOB-3721](https://karhoo.atlassian.net/browse/MOB-3721)
> MOB-3721 voice over improvements on rides list

- KarhooUISDK/CommonUI/UIConstants.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewController.swift
[MOB-3573](https://karhoo.atlassian.net/browse/MOB-3573)
Expanded the footer container and added shadow for top margin
> MOB-3573  [Checkout](UI) Add a bit more space between fleets T&C and Book button

- KarhooUISDK/Controllers/Payment/AddCard/AdyenCardRegistrationFlow.swift
- Podfile
- Podfile.lock
[MOB-3819](https://karhoo.atlassian.net/browse/MOB-3819)
> MOB-3819 add shopper locale to adyen peymant methods request

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Controllers/Payment/AddCard/BraintreeCardRegistrationFlow.swift
- KarhooUISDK/Extensions/UIColor+Extensions.swift
- KarhooUISDK/Screens/AddressScreen/AddressPresenter.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListPresenter.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewController.swift
- KarhooUISDKTests/TestCases/Routing/KarhooCardRegistrationFlowSpec.swift
- KarhooUISDKTests/TestCases/Screens/AddressScreen/KarhooAddressPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/KarhooBookingPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/QuoteList/KarhooQuoteListPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/TripAllocation/KarhooTripAllocationPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/CheckoutScreen/KarhooCheckoutPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/GuestCheckoutScreen/KarhooGuestCheckoutPresenterSpec.swift
[MOB-3703](https://karhoo.atlassian.net/browse/MOB-3848)
> MOB-3848 unit test fixes

- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Controllers/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Controllers/Payment/AddCard/BraintreeCardRegistrationFlow.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutPresenter.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/AddPaymentView/KarhooAddPaymentPresenter.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
[MOB-3812](https://karhoo.atlassian.net/browse/MOB-3812)
> MOB-3812 [Checkout] Adyen error handling fixed

- KarhooUISDK/Controllers/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Routing/BaseViewController.swift
[MOB-3661](https://karhoo.atlassian.net/browse/MOB-3661)
> MOB-3661 Set Adyen's Payment Methods modals to use light mode.

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Extensions/Swift+Then.swift
- KarhooUISDKTests/TestCases/Extension/SwiftThenSpec.swift
[MOB-3866](https://karhoo.atlassian.net/browse/MOB-3866)
> MOB-3866 'Then' added

- KarhooUISDK/CommonUI/UITexts.swift
[MOB-3703](https://karhoo.atlassian.net/browse/MOB-3703)
> MOB-3703 Keys removed from UIText

- KarhooUISDK/Screens/AddressScreen/AddressPresenter.swift
- KarhooUISDK/Screens/BookingScreen/QuoteCategoryBarMVP/KarhooQuoteCategoryBarPresenter.swift
- KarhooUISDK/Screens/BookingScreen/TripAllocationMVP/KarhooTripAllocationPresenter.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutPresenter.swift
- KarhooUISDK/Screens/DatePickerScreen/KarhooDatePickerPresenter.swift
- KarhooUISDK/Screens/TripScreen/KarhooTripPresenter.swift
- KarhooUISDK/Screens/TripSummaryScreen/KarhooTripSummaryPresenter.swift
- KarhooUISDK/Workers/Analytics.swift
- KarhooUISDKTests/Mocks/Common/MockAnalytics.swift
- KarhooUISDKTests/TestCases/Screens/AddressScreen/KarhooAddressPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/QuoteCategoryBar/KarhooQuoteCategoryBarPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/TripAllocation/KarhooTripAllocationPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/DatePickerScreen/DatePickerPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/TripScreen/TripDetails/KarhooTripPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/TripSummaryScreen/KarhooTripSummaryPresenterSpec.swift
[MOB-3879](https://karhoo.atlassian.net/browse/MOB-3879)
Deleted the not used events.
> MOB-3879 Clean the outdated analytics events in the UI SDK

- KarhooUISDK/Screens/PassengerDetails/PassengerDetailsViewController.swift
[MOB-3609](https://karhoo.atlassian.net/browse/MOB-3609)
The scrolling is now possible, but there are still UI issues related to keyboard handling.
To be fixed:
> bugfix/MOB-3609 Fix Passenger Details scroll

- KarhooUISDK/Screens/PassengerDetails/PassengerDetailsViewController.swift
[MOB-3860](https://karhoo.atlassian.net/browse/MOB-3860)
"activate next input field" removed since it was pretty buggy
> bugfix/MOB-3860 fix Passenger Details input focus issue

- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
[MOB-3916](https://karhoo.atlassian.net/browse/MOB-3916)
> MOB-3916 update translations

- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutPresenter.swift
- KarhooUISDK/UIComponents/LoyaltyView/KarhooLoyaltyPresenter.swift
[MOB-3898](https://karhoo.atlassian.net/browse/MOB-3898)
> update pre-auth handling in case of not eligible cases

- KarhooUISDK/Extensions/UIColor+Extensions.swift
- KarhooUISDK/Extensions/UIViewController+Extensions.swift
[MOB-3897](https://karhoo.atlassian.net/browse/MOB-3897)
- [ X ] Tech Debt
> MOB-3897: fix navigation bar appearance in dark mode

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
- README.md
[MOB-3893](https://karhoo.atlassian.net/browse/MOB-3893)
> MOB 3893 bump version to 1.7.2 [DEVELOP]

- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutPresenter.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewController+Extensions.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/AddPaymentView/KarhooAddPaymentPresenter.swift
[MOB-3910](https://karhoo.atlassian.net/browse/MOB-3910)
Solution works, but has potential to result is some backfires. Thorough tests required.
> bugfix/MOB-3910 Change user parameters binding to avoid backfire effect

- KarhooUISDK/CommonUI/Views/KarhooTextInputView/KarhooPhoneInputView.swift
- KarhooUISDK/Screens/PassengerDetails/PassengerDetailsViewController.swift
[MOB-3641](https://karhoo.atlassian.net/browse/MOB-3641)
Added default option to focus phone number after selecting country
> MOB-3641 Focus on the phone number field after phone prefix is selected

- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
Exported the most recent locale files from Phrase
> Updated translations from Phrase

- KarhooUISDK/CommonUI/Views/KarhooTextInputView/KarhooTextInputView.swift
[MOB-4000](https://karhoo.atlassian.net/browse/MOB-4000)
Before this changes app crashed if user tried to paste something into flight number / comment text view. It happened only for iOS 15+
- [ X] Bugfix 
> Mob 4000 paste delegate

- .circleci/config.yml
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Controllers/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Screens/Rides/RidesList/RidesListViewController.swift
- KarhooUISDKTests/Mocks/Service/MockPaymentService.swift
- KarhooUISDKTests/TestCases/Screens/AddressScreen/AddressSearchBar/KarhooAddressSearchBarPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/AddressScreen/KarhooAddressPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/TripAllocation/KarhooTripAllocationPresenterSpec.swift
- Podfile
- Podfile.lock
[MOB-4032](https://karhoo.atlassian.net/browse/MOB-4032)
> MOB-4032 [Accor-20]Cancelled orders need to appear in the "Past" trips list without closing and reopening

- KarhooUISDK/Screens/Rides/RideDetails/KarhooRideDetailsPresenter.swift
- KarhooUISDK/Screens/Rides/RideDetails/RideDetailsMVP.swift
- KarhooUISDK/Screens/Rides/RideDetails/RideDetailsViewController.swift
- KarhooUISDKTests/Mocks/Screen/Rides/Detail/MockRideDetailsView.swift
- Podfile.lock
- tack driver button added to RideDetails
- code reorganization in RideDetailsVC
[MOB-3986](https://karhoo.atlassian.net/browse/MOB-3986)
> feature/MOB-3986 Track driver button added to Ride Details

- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListPresenter.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteSortMVP/KarhooQuoteSortView.swift
- KarhooUISDKTests/TestCases/Routing/KarhooCardRegistrationFlowSpec.swift
[MOB-4039](https://karhoo.atlassian.net/browse/MOB-4039)
> setup price as a default sorting order

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/CommonUI/UIConstants.swift
- KarhooUISDK/CommonUI/Views/MainActionButton.swift
- KarhooUISDK/Screens/Rides/RideDetails/KarhooRideDetailsPresenter.swift
- KarhooUISDK/Screens/Rides/RideDetails/RideDetailsMVP.swift
- KarhooUISDK/Screens/Rides/RideDetails/RideDetailsViewController.swift
- KarhooUISDKTests/Mocks/Screen/Rides/Detail/MockRideDetailsView.swift
[MOB-3986](https://karhoo.atlassian.net/browse/MOB-3986)
> MOB-3986 Add Track Ride button

- .circleci/config.yml
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/CommonUI/UIConstants.swift
- KarhooUISDK/CommonUI/Views/KarhooTextInputView/KarhooTextInputView.swift
- KarhooUISDK/CommonUI/Views/MainActionButton.swift
- KarhooUISDK/Controllers/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListPresenter.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteSortMVP/KarhooQuoteSortView.swift
- KarhooUISDK/Screens/Rides/RideDetails/KarhooRideDetailsPresenter.swift
- KarhooUISDK/Screens/Rides/RideDetails/RideDetailsMVP.swift
- KarhooUISDK/Screens/Rides/RideDetails/RideDetailsViewController.swift
- KarhooUISDK/Screens/Rides/RidesList/RidesListViewController.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDKTests/Mocks/Screen/Rides/Detail/MockRideDetailsView.swift
- KarhooUISDKTests/Mocks/Service/MockPaymentService.swift
- KarhooUISDKTests/TestCases/Routing/KarhooCardRegistrationFlowSpec.swift
- KarhooUISDKTests/TestCases/Screens/AddressScreen/AddressSearchBar/KarhooAddressSearchBarPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/AddressScreen/KarhooAddressPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/TripAllocation/KarhooTripAllocationPresenterSpec.swift
- Podfile
- Podfile.lock
> Release 1.7.3 PR

- .circleci/config.yml
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/CommonUI/UIConstants.swift
- KarhooUISDK/CommonUI/Views/KarhooTextInputView/KarhooTextInputView.swift
- KarhooUISDK/CommonUI/Views/MainActionButton.swift
- KarhooUISDK/Controllers/Payment/AddCard/AdyenCardRegistrationFlow.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/KarhooQuoteListPresenter.swift
- KarhooUISDK/Screens/BookingScreen/QuoteListMVP/QuoteSortMVP/KarhooQuoteSortView.swift
- KarhooUISDK/Screens/Rides/RideDetails/KarhooRideDetailsPresenter.swift
- KarhooUISDK/Screens/Rides/RideDetails/RideDetailsMVP.swift
- KarhooUISDK/Screens/Rides/RideDetails/RideDetailsViewController.swift
- KarhooUISDK/Screens/Rides/RidesList/RidesListViewController.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDKTests/Mocks/Screen/Rides/Detail/MockRideDetailsView.swift
- KarhooUISDKTests/Mocks/Service/MockPaymentService.swift
- KarhooUISDKTests/TestCases/Routing/KarhooCardRegistrationFlowSpec.swift
- KarhooUISDKTests/TestCases/Screens/AddressScreen/AddressSearchBar/KarhooAddressSearchBarPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/AddressScreen/KarhooAddressPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/TripAllocation/KarhooTripAllocationPresenterSpec.swift
- Podfile
- Podfile.lock
JIRA
[MOB-4021](https://karhoo.atlassian.net/browse/MOB-4021)
DESCRIPTION
Release iOS UI SDK v1.7.3
> Release 1.7.3 PR (#307)

- KarhooUISDK.podspec
- README.md
> bump version in podspec and readme

- KarhooUISDK/Controllers/Payment/AddCard/AdyenCardRegistrationFlow.swift
[MOB-4008](https://karhoo.atlassian.net/browse/MOB-4008)
> MOB-4008 Adyen localization keys override tool

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/CommonUI/LoadingControls/LoadingBar/LoadingBar.swift
- KarhooUISDK/CommonUI/UIConstants.swift
- KarhooUISDK/Extensions/UIView+Extensions.swift
- KarhooUISDK/Screens/QuoteList/QuoteListTable/QuoteListTableViewController.swift
- KarhooUISDK/Screens/QuoteList/QuoteListViewController.swift
- KarhooUISDKTests/TestCases/Screens/GuestCheckoutScreen/KarhooGuestCheckoutPresenterSpec.swift
[MOB-4160](https://karhoo.atlassian.net/browse/MOB-4160)
> Feature/MOB-4160 quote list   progress bar

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Extensions/Date+Extensions.swift
- KarhooUISDK/Screens/QuoteList/QuoteListPresenter.swift
- KarhooUISDK/Workers/Analytics.swift
- KarhooUISDKTests/TestCases/Screens/GuestCheckoutScreen/KarhooGuestCheckoutPresenterSpec.swift
[MOB-4197](https://karhoo.atlassian.net/browse/MOB-XXXX)
> Feature/MOB-4197 -QuoteList - send fleetsShown event when quote list is dismissed

- KarhooUISDK/Screens/QuoteList/QuoteListFilters/FiltersViews/ItemsFilterView.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/QuoteFilterHandler.swift
- KarhooUISDKTests/Mocks/Screen/QuoteList/KarhooQuoteFilterHandlerSpec.swift
[MOB-4203](https://karhoo.atlassian.net/browse/MOB-4203)
> Feature/MOB-4203 quote list - remove all item from filters

- KarhooUISDK/API/KarhooComponents.swift
- KarhooUISDK/Controllers/JourneyDetails/JourneyDetails.swift
- KarhooUISDK/Screens/BookingScreen/Booking+MVPR.swift
- KarhooUISDK/Screens/BookingScreen/BookingRouter.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutPresenter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListCoordinator.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/LuggageCapacityFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/PassengerCapacityFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/QuoteListFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/QuoteFilterHandler.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/QuoteListFilters+MVPC .swift
- KarhooUISDK/Screens/QuoteList/QuoteListPresenter.swift
- KarhooUISDKTests/Mocks/Screen/BookingScreen/MockBookingRouter.swift
[MOB-3982](https://karhoo.atlassian.net/browse/MOB-3982)
> Feature/MOB-3982 Quote List - Pass luggages and passangers filter values  Booking api

- KarhooUISDK/CommonUI/LoadingControls/LoadingBar/LoadingBar.swift
- KarhooUISDK/Screens/QuoteList/QuoteListPresenter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListViewController.swift
[MOB-4212](https://karhoo.atlassian.net/browse/MOB-4212)
> Feature/MOB-4212 quote list - update refresh animation

- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteView.swift
- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteViewModel.swift
[MOB-4207](https://karhoo.atlassian.net/browse/MOB-4207)
> feature/MOB-4207 Quote fare label aligned with vehicle type label

- KarhooUISDK/CommonUI/Buttons/ItemFilterButton.swift
- KarhooUISDK/CommonUI/Buttons/MainActionButton.swift
- KarhooUISDK/CommonUI/UIConstants.swift
- KarhooUISDK/Extensions/UIView+Extensions.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewController.swift
- KarhooUISDK/Screens/QuoteList/QuoteListCoordinator.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/FiltersViews/FilterListItem.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/QuoteListFilters+MVPC .swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/QuoteListFiltersCorrdinator.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/QuoteListFiltersPresenter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/QuoteListFiltersViewController.swift
- KarhooUISDK/Screens/QuoteList/QuoteListPresenter.swift
[MOB-4234](https://karhoo.atlassian.net/browse/MOB-4234)
> Bugfix/MOB-4234 quote list - filters issues

- KarhooUISDK/API/KarhooComponents.swift
- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteCell.swift
- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteView.swift
- KarhooUISDK/Screens/QuoteList/QuoteListEmptyView.swift
- KarhooUISDK/Screens/QuoteList/QuoteListTable/QuoteListTableViewController.swift
- KarhooUISDK/Screens/QuoteList/QuoteListViewController.swift
- KarhooUISDK/UIComponents/AddressBarMVP/KarhooAddressBarView.swift
[MOB-4251](https://karhoo.atlassian.net/browse/MOB-4251)
> Feature/MOB-4251 quote list   change background color to light gray

- Podfile
- Podfile.lock
- KarhooSDK set to 1.6.3
- M1 configuration for dependencies added
[MOB-4222](https://karhoo.atlassian.net/browse/MOB-4222)
> MOB-4222 release - podfile update

- KarhooUISDK/Workers/VehicleRules/VehicleRulesProvider.swift
[MOB-4198](https://karhoo.atlassian.net/browse/MOB-4198)
> MOB-4198 - New vehicle rule matching pattern condition added

- AdyenPSP/AdyenThreeDSecureUtils.swift
- ClientSPM/ClientSPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/CommonUI/Views/IconPlusTextHorizontalView.swift
- KarhooUISDK/Routing/KarhooUISDKSceneCoordinator.swift
- KarhooUISDK/Screens/BookingScreen/BookingRouter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/EcoFriendlyFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/FleetCapabilitiesFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/LuggageCapacityFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/PassengerCapacityFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/QuoteListFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/VehicleClassFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/VehicleExtrasFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListPresenter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListSort/QuoteListSortCorrdinator.swift
- KarhooUISDK/Screens/QuoteList/QuoteListTable/QuoteListTable+MVPC.swift
- KarhooUISDK/Screens/QuoteList/QuoteListTable/QuoteListTablePresenter.swift
- KarhooUISDKTests/TestCases/Common/BraintreePaymentNonceProviderSpec.swift
- KarhooUISDKTests/TestCases/Common/BraintreeThreeDSecureProviderSpec.swift
- KarhooUISDKTests/TestCases/Routing/AdyenCardRegistrationFlowSpec.swift
- KarhooUISDKTests/TestCases/Routing/KarhooCardRegistrationFlowSpec.swift
- Package.swift
- Podfile
- Podfile.lock
- README.md
[MOB-4220](https://karhoo.atlassian.net/browse/MOB-4220)
> 1.9.1 develop sync

- Package.resolved
- Package.swift
[MOB-4311](https://karhoo.atlassian.net/browse/MOB-4311)
> use swift 5.6 and package.resolver in version 2.

- KarhooUISDK/UIComponents/LoyaltyView/KarhooLoyaltyPresenter.swift
- KarhooUISDK/UIComponents/LoyaltyView/KarhooLoyaltyView.swift
[MOB-4241](https://karhoo.atlassian.net/browse/MOB-4241)
> hide earning points description while waiting for backend response

- KarhooUISDK/CommonUI/MapMVP/MapMVP.swift
- KarhooUISDK/Screens/TripScreen/KarhooTripPresenter.swift
- KarhooUISDK/Screens/TripScreen/KarhooTripViewController.swift
- KarhooUISDK/Screens/TripScreen/Map/KarhooTripMapPresenter.swift
- KarhooUISDK/Screens/TripScreen/TripMVP.swift
- KarhooUISDKTests/Mocks/Screen/Trip/MockTripView.swift
[MOB-4226](https://karhoo.atlassian.net/browse/MOB-4226)
> Trip map initial focus change

- AdyenPSP/AdyenThreeDSecureUtils.swift
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- README.md
[MOB-4320](https://karhoo.atlassian.net/browse/MOB-4320)
> MOB-4320 release 1.9.2 (develop)

- AdyenPSP/AdyenThreeDSecureUtils.swift
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- README.md
> Release 1 9 3 [DEVELOP]

- AdyenPSP/AdyenThreeDSecureUtils.swift
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Extensions/UIViewController+Extensions.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- Podfile.lock
- README.md
> Post release 1 9 3 [MASTER]

- KarhooUISDK/CommonUI/MapMVP/AppleMapKit/KarhooMKMapView.swift
- KarhooUISDK/CommonUI/MapMVP/MapMVP.swift
- KarhooUISDK/Screens/AddressScreen/AddressMapView/KarhooAddressMapView.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/BookingScreen/Map/DestinationSetStrategy.swift
- KarhooUISDK/Screens/TripScreen/Map/KarhooTripMapPresenter.swift
- KarhooUISDKTests/Mocks/Common/MockKarhooMapView.swift
> Post release 1 9 3 v2

- AdyenPSP/AdyenThreeDSecureUtils.swift
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- Package.resolved
- Package.swift
- Podfile
- Podfile.lock
- README.md
[MOB-4371](https://karhoo.atlassian.net/browse/MOB-4371)
> Mob 4371 release 1 9 4 [DEVELOP]

- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutPresenter.swift
[MOB-4352](https://karhoo.atlassian.net/browse/MOB-4352)
> check terms and conditions before payment

- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
[MOB-4433](https://karhoo.atlassian.net/browse/MOB-4433)
> Clean-up unnecessary strings of UI SDK

- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutPresenter.swift
- KarhooUISDK/Workers/Analytics.swift
- KarhooUISDKTests/Mocks/Common/MockAnalytics.swift
[MOB-4376](https://karhoo.atlassian.net/browse/MOB-4376)
Adapt Checkout Tracking events to new flow
> 4376 Adapt Checkout Tracking events to new flow

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Podfile
- Podfile.lock
[MOB-4505](https://karhoo.atlassian.net/browse/MOB-4505)
Result:
> 4505 update Adyen to 4.7.2

- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
[MOB-3663](https://karhoo.atlassian.net/browse/MOB-3663)
> Align error codes

- Client/KarhooConfig.swift
- KarhooUISDK/API/KarhooUISDKConfiguration.swift
- KarhooUISDK/Screens/PrebookConfirmationScreen/KarhooBookingConfirmationView.swift
- KarhooUISDK/Screens/PrebookConfirmationScreen/KarhooBookingConfirmationViewModel.swift
- KarhooUISDKTestUtils/KarhooTestConfiguration.swift
- Podfile.lock
> MOB-4537 add-to-calendar feature flag added to configuration

- KarhooUISDK/CommonUI/AddressView/AddressView.swift
- KarhooUISDK/Screens/PrebookConfirmationScreen/KarhooBookingConfirmationView.swift
> Add one-line design to addres-view

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/API/KarhooUIScreenRouting.swift
- KarhooUISDK/API/ScreenBuilders.swift
- KarhooUISDK/Builders/BookingConfirmationBuilder.swift
- KarhooUISDK/Controllers/JourneyDetails/JourneyDetails.swift
> Set BookingConfirmation component accessable for public usage

- KarhooUISDK/Controllers/NavigationController.swift
- KarhooUISDK/Screens/QuoteList/QuoteListViewController.swift
> MOB-4537 - regression - ensure proper nav bar design is set

- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutPresenter.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/PassengerCellViewController.swift
> MOB-4537 Fix missing pre-defined passenger data in checkout scene

- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutPresenter.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewController.swift
> enable button

- AdyenPSP/AdyenThreeDSecureUtils.swift
- ClientSPM/ClientSPM/ClientSPMApp.swift
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- Package.swift
- Podfile.lock
- README.md
[MOB-4499](https://karhoo.atlassian.net/browse/MOB-4499)
> MOB-4499 release 1.10.0

- ClientSPM/ClientSPM.xcodeproj/project.pbxproj
- ClientSPM/ClientSPM/ClientSPMApp.swift
[MOB-4499](https://karhoo.atlassian.net/browse/MOB-4499)
> add calendar permission to spm client

- AdyenPSP/AdyenThreeDSecureUtils.swift
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Package.resolved
- README.md
> release 1.10.1 develop

- KarhooUISDK.xcodeproj/project.pbxproj
- fastlane/Fastfile
[MOB-4552](https://karhoo.atlassian.net/browse/MOB-4552)
> bugfix/MOB-4552 Bitrise not building cocoapods client anymore

- AdyenPSP/AdyenCardRegistrationFlow.swift
- Podfile
- Podfile.lock
[MOB-4528](https://karhoo.atlassian.net/browse/MOB-4528)
> MOB-4528 Pass showStorePaymentMethod property to API adyen call

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/PriceDetails/KarhooCheckoutPriceDetailsView.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/PriceDetails/KarhooCheckoutPriceDetailsViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/NewCheckout+MVPC.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/NewCheckoutCoordinator.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/NewCheckoutPresenter.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/NewCheckoutViewController.swift
[MOB-4441](https://karhoo.atlassian.net/browse/MOB-4441)
[MOB-4441]: https://karhoo.atlassian.net/browse/MOB-4441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> price details bottom sheet

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Screens/CheckoutScreen/Checkout/VehicleDetailsCard.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/NewVehicleCapacity.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/NewCheckoutPresenter.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/NewCheckoutView.swift
- KarhooUISDK/Screens/CheckoutScreen/Workers/KarhooFreeCancelationTextWorker.swift
- KarhooUISDK/Screens/Rides/RidesList/RideCell/RideCellViewModel.swift
- KarhooUISDK/ViewModels/TripMetaDataViewModel.swift
[MOB-4402](https://karhoo.atlassian.net/browse/MOB-4402)
[MOB-4456](https://karhoo.atlassian.net/browse/MOB-4456)
Only PR fixes
[MOB-4402]: https://karhoo.atlassian.net/browse/MOB-4402?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MOB-4456]: https://karhoo.atlassian.net/browse/MOB-4456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJ …
> pr fixes cherry picked from commit: ""pr fixes 2ae189b"

- .swiftlint.yml
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Screens/BookingScreen/Booking+MVPR.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/DetailsCellViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/NewCheckout+MVPC.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/NewCheckoutCoordinator.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/NewCheckoutPresenter.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/NewCheckoutView.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/ViewModels/CommentCellViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/ViewModels/FlightNumberCellViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/ViewModels/PassengerDetailsCellViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/ViewModels/TrainNumberCellViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/Workers/KarhooNewCheckoutPassengerDetailsWorker.swift
- KarhooUISDK/Screens/CheckoutScreen/NewCheckout/Workers/KarhooNewCheckoutPaymentAndBookingWorker.swift
- KarhooUISDK/UIComponents/LegalNotice/LegalNoticeStringBuilder.swift
- KarhooUISDK/UIComponents/TermsConditionsView/SwiftUI/KarhooTermsConditionsView.swift
- KarhooUISDK/UIComponents/TermsConditionsView/SwiftUI/KarhooTermsConditionsViewModel.swift
[MOB-4564](https://karhoo.atlassian.net/browse/MOB-4564)
[MOB-4564]: https://karhoo.atlassian.net/browse/MOB-4564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feature/mob-4564 new checkout - happy path handling

- KarhooUISDK/CommonUI/AddToCalendar/AddToCalendarView.swift
- KarhooUISDK/Screens/PrebookConfirmationScreen/KarhooBookingConfirmationView.swift
[MOB-4458](https://karhoo.atlassian.net/browse/MOB-4458)
[MOB-4458]: https://karhoo.atlassian.net/browse/MOB-4458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4458 change accessiblity values

- KarhooUISDK/CommonUI/Views/FormButtonView/FormButton.swift
[MOB-4481](https://karhoo.atlassian.net/browse/MOB-4481)
[MOB-4481]: https://karhoo.atlassian.net/browse/MOB-4481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> test trunk change

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/CommonUI/AddressView/AddressView.swift
- KarhooUISDK/CommonUI/VehicleCapacity.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/CheckoutView.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/DetailsCell/DetailsCellView.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/Loyalty/LoyaltyView.swift
- KarhooUISDK/Screens/CheckoutScreen/VehicleDetailsCard.swift
[MOB-4560](https://karhoo.atlassian.net/browse/MOB-4560)
[MOB-4560]: https://karhoo.atlassian.net/browse/MOB-4560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4560 reduce number of font weights and sizes in the checkout screen

- KarhooUISDKUITests/Checkout/CheckoutSnapshotSpec.swift
[MOB-4573](https://karhoo.atlassian.net/browse/MOB-4573)
[MOB-4573]: https://karhoo.atlassian.net/browse/MOB-4573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4573 snapshot cleanup

- KarhooUISDK/CommonUI/Views/KarhooMaterialDesignTextField.swift
- KarhooUISDK/Extensions/UITextView+SwiftUI.swift
- KarhooUISDK/Extensions/View+Extensions.swift
[MOB-4578](https://karhoo.atlassian.net/browse/MOB-4578)
[MOB-4578]: https://karhoo.atlassian.net/browse/MOB-4578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4578 fix dark mode on checkout

- KarhooUISDK/Workers/Loyalty/LoyaltyWorker.swift
[MOB-4578](https://karhoo.atlassian.net/browse/MOB-4578)
[MOB-4578]: https://karhoo.atlassian.net/browse/MOB-4578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4578 fix loyalty logic

- KarhooUISDK/Models/LoyalityMode.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/Workers/KarhooCheckoutBookingWorker.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/Loyalty/LoyaltyView.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/Loyalty/LoyaltyViewModel.swift
- KarhooUISDK/Workers/Loyalty/LoyaltyWorker.swift
- KarhooUISDKTestUtils/Mocks/Common/MockLoyaltyWorker.swift
- KarhooUISDKTests/TestCases/Screens/CheckoutScreen/CheckoutViewModelSpec.swift
[MOB-4589](https://karhoo.atlassian.net/browse/MOB-4589)
[MOB-4589]: https://karhoo.atlassian.net/browse/MOB-4589?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4589 fix loyalty on booking confirmation screen

- KarhooUISDK/CommonUI/BaseControls/BaseSelectionView/BaseSelectionView.swift
- KarhooUISDK/CommonUI/Buttons/DropDownButton.swift
- KarhooUISDK/CommonUI/Views/ErrorBannerView.swift
- KarhooUISDK/CommonUI/Views/KarhooTextField/KarhooTextField.swift
- KarhooUISDK/Controllers/AddressProvider/AddressSearchProvider.swift
- KarhooUISDK/Screens/Rides/RideDetails/RatingViewMVP/RateButton/RateButton.swift
- KarhooUISDK/Screens/Rides/RideDetails/RatingViewMVP/RatingViewMVP.swift
- KarhooUISDK/Screens/Rides/RideDetails/TripMetaData/FeedbackButton/FeedbackButtonMVP.swift
- KarhooUISDK/Screens/Rides/RideDetails/TripMetaData/KarhooTripMetaDataView.swift
- KarhooUISDK/Screens/Rides/UIPageControl/TwoPageViewController.swift
- KarhooUISDK/Screens/TripScreen/TripDetails/TripInfoView/TripInfoView.swift
- KarhooUISDK/Workers/ConstraintSwitcher/ConstraintSwitcher.swift
- KarhooUISDK/Workers/KeyboardSizeProvider.swift
> MOB-0000 remove warnings

- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/en.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/id.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/ja.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDK/Translations/pl.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-BR.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-PT.lproj/Localizable.strings
- KarhooUISDK/Translations/ru.lproj/Localizable.strings
- KarhooUISDK/Translations/th.lproj/Localizable.strings
- KarhooUISDK/Translations/zh-Hans.lproj/Localizable.strings
[MOB-4578](https://karhoo.atlassian.net/browse/MOB-4578)
[MOB-4578]: https://karhoo.atlassian.net/browse/MOB-4578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4578 add newest translations

- ClientSPM/ClientSPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Package.swift
> MOB-0000 SPM updated

- KarhooUISDK/Screens/CheckoutScreen/Components/Loyalty/LoyaltyViewModel.swift
- KarhooUISDK/UIComponents/LegalNotice/KarhooLegalNoticeViewModel.swift
- KarhooUISDK/Workers/Loyalty/LoyaltyWorker.swift
[MOB-4258](https://karhoo.atlassian.net/browse/MOB-4258)
[MOB-4258]: https://karhoo.atlassian.net/browse/MOB-4258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4258 checkout loyalty fixes

- AdyenPSP/AdyenThreeDSecureUtils.swift
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Package.resolved
- Package.swift
- Podfile
- Podfile.lock
- README.md
[MOB-4590](https://karhoo.atlassian.net/browse/MOB-4590)
[MOB-4590]: https://karhoo.atlassian.net/browse/MOB-4590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4590 release 1.11.0

- Client/ViewController.swift
- Client/fr.lproj/Localizable.strings
- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/UIComponents/LegalNotice/LegalNoticeStringBuilder.swift
[MOB-4378](https://karhoo.atlassian.net/browse/MOB-4378)
[MOB-4378]: https://karhoo.atlassian.net/browse/MOB-4378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4378 adapt drop in client

- ClientSPM/ClientSPM.xcodeproj/project.pbxproj
- ClientSPM/ClientSPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ClientSPM/ClientSPM/de.lproj/Localizable.strings
- ClientSPM/ClientSPM/en.lproj/Localizable.strings
- ClientSPM/ClientSPM/es.lproj/Localizable.strings
- ClientSPM/ClientSPM/fr.lproj/Localizable.strings
- ClientSPM/ClientSPM/id.lproj/Localizable.strings
- ClientSPM/ClientSPM/it.lproj/Localizable.strings
- ClientSPM/ClientSPM/ja.lproj/Localizable.strings
- ClientSPM/ClientSPM/nl.lproj/Localizable.strings
- ClientSPM/ClientSPM/pl.lproj/Localizable.strings
- ClientSPM/ClientSPM/pt-BR.lproj/Localizable.strings
- ClientSPM/ClientSPM/pt-PT.lproj/Localizable.strings
- ClientSPM/ClientSPM/ru.lproj/Localizable.strings
- ClientSPM/ClientSPM/th.lproj/Localizable.strings
- ClientSPM/ClientSPM/zh-Hans.lproj/Localizable.strings
[MOB-4378](https://karhoo.atlassian.net/browse/MOB-4378)
[MOB-4378]: https://karhoo.atlassian.net/browse/MOB-4378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4378 update client spm localisations

- Client/fr.lproj/Localizable.strings
[MOB-4378](https://karhoo.atlassian.net/browse/MOB-4378)
[MOB-4378]: https://karhoo.atlassian.net/browse/MOB-4378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4378 Small changes to align with Android texts

- Client/fr.lproj/Localizable.strings
- ClientSPM/ClientSPM/fr.lproj/Localizable.strings
- KarhooUISDK/Screens/CheckoutScreen/Checkout/CheckoutView.swift
[MOB-4378](https://karhoo.atlassian.net/browse/MOB-4378)
[MOB-4378]: https://karhoo.atlassian.net/browse/MOB-4378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4378 Add longer text for the legal notice title

- KarhooUISDK/Workers/VehicleRules/VehicleRulesProvider.swift
[MOB-4651](https://karhoo.atlassian.net/browse/MOB-4651)
[MOB-4651]: https://karhoo.atlassian.net/browse/MOB-4651?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4651 force moto image regardless of tags

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Screens/QuoteList/KarhooQuoteListViewController.swift
- KarhooUISDK/Screens/QuoteList/KarhooQuoteListViewModel.swift
- KarhooUISDK/Screens/QuoteList/QuoteListTable/KarhooQuoteListTableViewController.swift
- KarhooUISDK/Screens/QuoteList/QuoteListTable/QuoteListTable+MVPC.swift
[MOB-4149](https://karhoo.atlassian.net/browse/MOB-4149)
[MOB-4149]: https://karhoo.atlassian.net/browse/MOB-4149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4149-Quote-Increase-refresh-speed-and-add-animation-when-a-new-quote-appears-in-the-list

- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/VehicleClassFilter.swift
[MOB-4303](https://karhoo.atlassian.net/browse/MOB-4303)
[MOB-4303]: https://karhoo.atlassian.net/browse/MOB-4303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4303-Quote-Add-standard-as-vehicle-category-filters

- KarhooUISDK/Screens/BookingScreen/Map/PickupOnlyStrategy.swift
[MOB-4117](https://karhoo.atlassian.net/browse/MOB-4117)
[MOB-4117]: https://karhoo.atlassian.net/browse/MOB-4117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4117 - stop updating map location once pick-up only strategy is selected

- KarhooUISDK/CommonUI/Buttons/MainActionButton.swift
- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Controllers/NavigationController.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/en.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/id.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/ja.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDK/Translations/pl.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-BR.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-PT.lproj/Localizable.strings
- KarhooUISDK/Translations/ru.lproj/Localizable.strings
- KarhooUISDK/Translations/th.lproj/Localizable.strings
- KarhooUISDK/Translations/zh-Hans.lproj/Localizable.strings
[MOB-4681](https://karhoo.atlassian.net/browse/MOB-4681)
[MOB-4681]: https://karhoo.atlassian.net/browse/MOB-4681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4681-iOS-Display-2-buttons-for-the-new-ride-planning-flow-NOW-and-LATER

- AdyenPSP/AdyenThreeDSecureUtils.swift
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Extensions/Bundle+extensions/Bundle+current.swift
- README.md
[MOB-4673](https://karhoo.atlassian.net/browse/MOB-4673)
[MOB-4673]: https://karhoo.atlassian.net/browse/MOB-4673?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4673 missing cocoapods assets

- AdyenPSP/AdyenThreeDSecureUtils.swift
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Extensions/Bundle+extensions/Bundle+current.swift
- README.md
* rename cocoapods resource bundle
* version bump 1.11.1
[MOB-4687](https://karhoo.atlassian.net/browse/MOB-4687)
[MOB-4687]: https://karhoo.atlassian.net/browse/MOB-4687?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4687 post-release v 1.11.1

- KarhooUISDK/Assets/Assets.xcassets/kh_uisdk_cross_in_circle.imageset/Contents.json
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/UIComponents/AddressBarMVP/AddressBarFieldMVP/KarhooAddressBarFieldView.swift
- KarhooUISDK/UIComponents/AddressBarMVP/KarhooAddressBarView.swift
[MOB-4683](https://karhoo.atlassian.net/browse/MOB-4683)
[MOB-4683]: https://karhoo.atlassian.net/browse/MOB-4683?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4683-Provide-hiding-capability-for-the-calendar-button-on-the-Address-picker

- AdyenPSP/AdyenPaymentManager.swift
- BraintreePSP/BraintreePaymentManager.swift
- KarhooUISDK/Payments/PaymentManager.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/Workers/KarhooCheckoutBookingWorker.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/Workers/KarhooCheckoutPaymentWorker.swift
- KarhooUISDKTestUtils/Mocks/Classes/MockThreeDSecureProvider.swift
- KarhooUISDKTestUtils/Mocks/Common/MockCheckoutPaymentWorker.swift
- KarhooUISDKTestUtils/Mocks/Routing/MockCardRegistrationFlow.swift
- KarhooUISDKTestUtils/Mocks/Service/MockPaymentManager.swift
- KarhooUISDKTests/TestCases/Common/BraintreePaymentNonceProviderSpec.swift
- KarhooUISDKTests/TestCases/Screens/CheckoutScreen/CheckoutBookingWorkerSpec.swift
[MOB-4628](https://karhoo.atlassian.net/browse/MOB-4628)
[MOB-4628]: https://karhoo.atlassian.net/browse/MOB-4628?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4628 fix payment unit tests

- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewModel.swift
- KarhooUISDK/Screens/DatePickerScreen/DatePickerMVP.swift
- KarhooUISDK/Screens/DatePickerScreen/KarhooDatePickerPresenter.swift
- KarhooUISDK/Screens/DatePickerScreen/View/DatePickerViewController.swift
- KarhooUISDK/Workers/Formatters/KarhooDateFormatter.swift
- KarhooUISDK/Workers/KarhooCountryParser.swift
- KarhooUISDKTestUtils/Mocks/Screen/DatePickerScreen/View/MockDatePickerView.swift
- Podfile.lock
[MOB-4615](https://karhoo.atlassian.net/browse/MOB-4615)
[MOB-4615]: https://karhoo.atlassian.net/browse/MOB-4615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4615 improve time handling

- KarhooUISDK/CommonUI/MapMVP/AppleMapKit/KarhooMKMapView.swift
- KarhooUISDK/CommonUI/UIConstants.swift
- KarhooUISDK/Screens/BookingScreen/AddressBar/BookingAddressBarPresenter.swift
- KarhooUISDK/Screens/BookingScreen/Booking+MVPR.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/DatePickerScreen/KarhooDatePickerPresenter.swift
- KarhooUISDK/Screens/DatePickerScreen/View/DatePickerViewController.swift
- KarhooUISDK/Screens/DatePickerScreen/View/DatePickerViewController.xib
- KarhooUISDK/UIComponents/AddressBarMVP/AddressBarMVP.swift
- KarhooUISDK/UIComponents/AddressBarMVP/PrebookFieldMVP/KarhooPrebookFieldView.swift
- Podfile.lock
[MOB-4685](https://karhoo.atlassian.net/browse/MOB-4685)
[MOB-4685]: https://karhoo.atlassian.net/browse/MOB-4685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4685 schedule a ride UX, address view tweaks, address picker tweaks, map tweaks

- AdyenPSP/AdyenPaymentManager.swift
- BraintreePSP/BraintreePaymentManager.swift
> MOB-0000 Client SPM fix

- BraintreePSP/BraintreeCardRegistrationFlow.swift
- BraintreePSP/BraintreePaymentScreensBuilder.swift
- KarhooUISDK/Builders/PaymentScreenBuilder.swift
- KarhooUISDKTestUtils/Mocks/Builders/MockPaymentScreenBuilder.swift
[MOB-4657](https://karhoo.atlassian.net/browse/MOB-4657)
[MOB-4657]: https://karhoo.atlassian.net/browse/MOB-4657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4657 add card save switch

- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/BookingScreen/KarhooCoverageCheckWorker.swift
- KarhooUISDK/Screens/BookingScreen/NoCoverageView.swift
[MOB-4711](https://karhoo.atlassian.net/browse/MOB-4711)
[MOB-4711]: https://karhoo.atlassian.net/browse/MOB-4711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4711 hide rode planning bottom container if it is not needed

- BraintreePSP/BraintreePaymentScreensBuilder.swift
[MOB-4709](https://karhoo.atlassian.net/browse/MOB-4709)
[MOB-4709]: https://karhoo.atlassian.net/browse/MOB-4709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4709 remove cardholder name

- KarhooUISDK/CommonUI/VehicleCapacity.swift
- KarhooUISDK/Screens/CheckoutScreen/VehicleDetailsCard.swift
- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteVehicleCapacityView.swift
- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteView.swift
- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteViewModel.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/LuggageCapacityFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/PassengerCapacityFilter.swift
- KarhooUISDKTests/TestCases/Common/ViewModel/QuoteCellViewModelSpec.swift
- Podfile
- Podfile.lock
[MOB-4100](https://karhoo.atlassian.net/browse/MOB-4100)
[MOB-4100]: https://karhoo.atlassian.net/browse/MOB-4100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4100 Display 0 or don't display depending on API response

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/Extensions/UIStatusBarStyle+Extensions.swift
- KarhooUISDK/Routing/UINavigation.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewController.swift
- KarhooUISDK/Screens/DatePickerScreen/View/DatePickerViewController.swift
- KarhooUISDK/Screens/QuoteList/KarhooQuoteListViewController.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/QuoteListFiltersViewController.swift
- KarhooUISDK/Screens/QuoteList/QuoteListSort/KarhooQuoteListSortViewController.swift
- KarhooUISDK/Screens/QuoteList/QuoteListTable/KarhooQuoteListTableViewController.swift
- KarhooUISDK/Screens/SideMenu/SideMenuContent/MenuContentViewController.swift
- KarhooUISDK/Screens/SideMenu/SideMenuViewController.swift
- KarhooUISDK/Screens/TripScreen/KarhooTripViewController.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/KarhooBookingViewController+BuilderSpec.swift
- KarhooUISDKTests/TestCases/Screens/DatePickerScreen/DatePickerPresenterSpec.swift
[MOB-4725](https://karhoo.atlassian.net/browse/MOB-4725)
[MOB-4725]: https://karhoo.atlassian.net/browse/MOB-4725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4725 farechoice map hiding below top navigation bar on ride planning scene

- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewModel.swift
[MOB-4659](https://karhoo.atlassian.net/browse/MOB-4659)
[MOB-4659]: https://karhoo.atlassian.net/browse/MOB-4659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4659 fix incorrect checkout screen state

- AdyenPSP/AdyenThreeDSecureUtils.swift
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Package.swift
- README.md
[MOB-4764](https://karhoo.atlassian.net/browse/MOB-4764)
[MOB-4764]: https://karhoo.atlassian.net/browse/MOB-4764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4764 Release 1.12 preparation

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/FeatureFlags/feature_flag.json
- KarhooUISDK/feature_flag.json
[MOB-4757](https://karhoo.atlassian.net/browse/MOB-4757)
[MOB-4757]: https://karhoo.atlassian.net/browse/MOB-4757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4757 feature flag file

- Client/ViewController.swift
- Podfile.lock
[MOB-0000](https://karhoo.atlassian.net/browse/MOB-0000)
> MOB-0000 add error alert in client

- KarhooUISDK/FeatureFlags/FeatureFlagsUpdater.swift
[MOB-4765](https://karhoo.atlassian.net/browse/MOB-4765)
[MOB-4765]: https://karhoo.atlassian.net/browse/MOB-4765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4765 update json url

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/API/KarhooUISDKConfiguration.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/en.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/id.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/ja.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDK/Translations/pl.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-BR.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-PT.lproj/Localizable.strings
- KarhooUISDK/Translations/ru.lproj/Localizable.strings
- KarhooUISDK/Translations/th.lproj/Localizable.strings
- KarhooUISDK/Translations/zh-Hans.lproj/Localizable.strings
- README.md
[MOB-4770](https://karhoo.atlassian.net/browse/MOB-4770)
[MOB-4770]: https://karhoo.atlassian.net/browse/MOB-4770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4770-release-1.12.1

- KarhooUISDK/FeatureFlags/feature_flag.json
[MOB-4706](https://karhoo.atlassian.net/browse/MOB-4706)
[MOB-4706]: https://karhoo.atlassian.net/browse/MOB-4706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4706 Update feature_flag.json

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/API/KarhooUISDKConfiguration.swift
- KarhooUISDK/Assets/Assets.xcassets/QuoteBadges/kh_uisdk_vehicle_badge_economy.imageset/Contents.json
- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteView.swift
- README.md
[MOB-4785](https://karhoo.atlassian.net/browse/MOB-4785)
[MOB-4785]: https://karhoo.atlassian.net/browse/MOB-4785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Mob-4785 iOS UISDK 1.12.2 release

- KarhooUISDK/CommonUI/AddressView/AddressView.swift
- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/CheckoutView.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewModel.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/en.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/id.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/ja.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDK/Translations/pl.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-BR.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-PT.lproj/Localizable.strings
- KarhooUISDK/Translations/ru.lproj/Localizable.strings
- KarhooUISDK/Translations/th.lproj/Localizable.strings
- KarhooUISDK/Translations/zh-Hans.lproj/Localizable.strings
- KarhooUISDK/UIComponents/AddressBarMVP/AddressBarFieldMVP/KarhooAddressBarFieldView.swift
- KarhooUISDK/Workers/Formatters/KarhooDateFormatter.swift
- KarhooUISDKTestUtils/Mocks/Common/MockDataFormatterType.swift
- Podfile.lock
[MOB-4563](https://karhoo.atlassian.net/browse/MOB-4563)
[MOB-4563]: https://karhoo.atlassian.net/browse/MOB-4563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4563 add accessibility texts to close SDK and delete address buttons

- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/CommonUI/VehicleCapacity.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/DetailsCell/DetailsCellView.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/DetailsCell/DetailsCellViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/ViewModels/CommentCellViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/ViewModels/FlightNumberCellViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/ViewModels/PassengerDetailsCellViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/ViewModels/TrainNumberCellViewModel.swift
- KarhooUISDK/Screens/CheckoutScreen/VehicleDetailsCard.swift
- KarhooUISDK/Screens/QuoteList/KarhooQuoteListViewController.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/en.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/id.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/ja.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDK/Translations/pl.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-BR.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-PT.lproj/Localizable.strings
- KarhooUISDK/Translations/ru.lproj/Localizable.strings
- KarhooUISDK/Translations/th.lproj/Localizable.strings
- KarhooUISDK/Translations/zh-Hans.lproj/Localizable.strings
- Podfile.lock
[MOB-4772](https://karhoo.atlassian.net/browse/MOB-4772)
[MOB-4772]: https://karhoo.atlassian.net/browse/MOB-4772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4772 checkout accessibility improvements

- KarhooUISDK/CommonUI/LoadingControls/LoadingImageView/LoadingImageView.swift
- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteVehicleCapacityView.swift
- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteView.swift
- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteViewModel.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/en.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/id.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/ja.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDK/Translations/pl.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-BR.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-PT.lproj/Localizable.strings
- KarhooUISDK/Translations/ru.lproj/Localizable.strings
- KarhooUISDK/Translations/th.lproj/Localizable.strings
- KarhooUISDK/Translations/zh-Hans.lproj/Localizable.strings
[MOB-4720](https://karhoo.atlassian.net/browse/MOB-4720)
[MOB-4720]: https://karhoo.atlassian.net/browse/MOB-4720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4720 quote list accessibility improvements

- KarhooUISDK/CommonUI/MapMVP/AppleMapKit/KarhooMKMapView.swift
- KarhooUISDK/CommonUI/MapMVP/AppleMapKit/MapAnnotationViewModel.swift
- KarhooUISDK/CommonUI/MapMVP/MapMVP.swift
- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Screens/AddressScreen/AddressMapView/KarhooAddressDisplayView.swift
- KarhooUISDK/Screens/AddressScreen/AddressMapView/KarhooAddressMapView.swift
- KarhooUISDK/Screens/TripScreen/Map/KarhooTripMapPresenter.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/en.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/id.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/ja.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDK/Translations/pl.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-BR.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-PT.lproj/Localizable.strings
- KarhooUISDK/Translations/ru.lproj/Localizable.strings
- KarhooUISDK/Translations/th.lproj/Localizable.strings
- KarhooUISDK/Translations/zh-Hans.lproj/Localizable.strings
- KarhooUISDK/UIComponents/AddressBarMVP/KarhooAddressBarView.swift
- KarhooUISDK/UIComponents/TermsConditionsView/KarhooTermsConditionsView.swift
[MOB-4772](https://karhoo.atlassian.net/browse/MOB-4772)
[MOB-4772]: https://karhoo.atlassian.net/browse/MOB-4772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4772 general accessibility improvements

- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/FeatureFlags/KarhooFeatureFlagProvider.swift
- KarhooUISDK/FeatureFlags/LoyaltyFeatureFlags.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDK/Workers/Loyalty/LoyaltyWorker.swift
- KarhooUISDKTests/TestCases/Common/MockFeatureFlagsProvider.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/KarhooBookingPresenterSpec.swift
[MOB-4766](https://karhoo.atlassian.net/browse/MOB-4766)
[MOB-4766]: https://karhoo.atlassian.net/browse/MOB-4766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4766 merge feature flags

- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Extensions/KarhooSDKExtensions/QuoteVehicle+Extensions.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/KarhooCheckoutViewModel.swift
- KarhooUISDK/Screens/QuoteList/QuoteCell/QuoteViewModel.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/en.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/id.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/ja.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDK/Translations/pl.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-BR.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-PT.lproj/Localizable.strings
- KarhooUISDK/Translations/ru.lproj/Localizable.strings
- KarhooUISDK/Translations/th.lproj/Localizable.strings
- KarhooUISDK/Translations/zh-Hans.lproj/Localizable.strings
[MOB-4772](https://karhoo.atlassian.net/browse/MOB-4772)
[MOB-4772]: https://karhoo.atlassian.net/browse/MOB-4772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4772 - fix vehicle image accessibility label

- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Screens/QuoteList/KarhooQuoteListViewModel.swift
- KarhooUISDK/Screens/QuoteList/QuoteList+MVPC.swift
- KarhooUISDK/Screens/QuoteList/QuoteListTable/KarhooQuoteListTableViewModel.swift
- KarhooUISDKUITests/QuoteList/QuoteListSnapshotSpec.swift
[MOB-4359](https://karhoo.atlassian.net/browse/MOB-4359)
[MOB-4359]: https://karhoo.atlassian.net/browse/MOB-4359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4359 fix no coverage error message

- ClientSPM/ClientSPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/API/KarhooUISDKConfiguration.swift
- Package.resolved
- Package.swift
- README.md
[MOB-4785](https://karhoo.atlassian.net/browse/MOB-4785)
[MOB-4785]: https://karhoo.atlassian.net/browse/MOB-4785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4785 i os UI sdk 1.12.3 release

- KarhooUISDK/CommonUI/AddressView/AddressView.swift
- KarhooUISDK/Extensions/KarhooSDKExtensions/JourneyDetails+Extensions.swift
- KarhooUISDK/Extensions/String+Extensions.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/CheckoutView.swift
- Podfile.lock
[MOB-4776](https://karhoo.atlassian.net/browse/MOB-4776)
[MOB-4776]: https://karhoo.atlassian.net/browse/MOB-4776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4776 remove adderss info duplication

- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/Screens/CheckoutScreen/Components/Loyalty/LoyaltyView.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/en.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/id.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/ja.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDK/Translations/pl.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-BR.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-PT.lproj/Localizable.strings
- KarhooUISDK/Translations/ru.lproj/Localizable.strings
- KarhooUISDK/Translations/th.lproj/Localizable.strings
- KarhooUISDK/Translations/zh-Hans.lproj/Localizable.strings
[MOB-4769](https://karhoo.atlassian.net/browse/MOB-4769)
[MOB-4769]: https://karhoo.atlassian.net/browse/MOB-4769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4769 accesibility on loyalty

- KarhooUISDK/CommonUI/AddressView/AddressView.swift
- KarhooUISDK/CommonUI/UITexts.swift
- KarhooUISDK/UIComponents/AddressBarMVP/AddressBarFieldMVP/AddressBarFieldMVP.swift
- KarhooUISDK/UIComponents/AddressBarMVP/AddressBarFieldMVP/KarhooAddressBarFieldView.swift
- KarhooUISDK/UIComponents/AddressBarMVP/KarhooAddressBarView.swift
[MOB-4587](https://karhoo.atlassian.net/browse/MOB-4587)
[MOB-4587]: https://karhoo.atlassian.net/browse/MOB-4587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4587 add prefix description

- KarhooUISDK/CommonUI/AddressView/AddressView.swift
[MOB-4776](https://karhoo.atlassian.net/browse/MOB-4776)
[MOB-4776]: https://karhoo.atlassian.net/browse/MOB-4776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4776 left align text in static address component

- KarhooUISDK/UIComponents/TermsConditionsView/TermsConditionsStringBuilder.swift
[MOB-0000](https://karhoo.atlassian.net/browse/MOB-0000)
> MOB-0000 debug value removed

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/API/KarhooUISDKConfiguration.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/en.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/id.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/ja.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDK/Translations/pl.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-BR.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-PT.lproj/Localizable.strings
- KarhooUISDK/Translations/ru.lproj/Localizable.strings
- KarhooUISDK/Translations/th.lproj/Localizable.strings
- KarhooUISDK/Translations/zh-Hans.lproj/Localizable.strings
- README.md
[MOB-4815](https://karhoo.atlassian.net/browse/MOB-4815)
[MOB-4815]: https://karhoo.atlassian.net/browse/MOB-4815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4815 bump version + update translationsd

- AdyenPSP/AdyenCardRegistrationFlow.swift
- Client/KarhooConfig.swift
- Client/ViewController.swift
- ClientSPM/ClientSPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- KarhooUISDK/Screens/CheckoutScreen/Checkout/Workers/KarhooCheckoutBookingWorker.swift
- KarhooUISDKTestUtils/KarhooTestConfiguration.swift
- KarhooUISDKTestUtils/Mocks/Service/MockUserService.swift
- KarhooUISDKTests/TestCases/Common/CancelRideBehaviourSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/KarhooBookingPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/Map/EmptyBookingMapStrategySpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/Map/PickupOnlyStrategySpec.swift
- KarhooUISDKTests/TestCases/Screens/BookingScreen/TripAllocation/KarhooTripAllocationPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/CheckoutScreen/CheckoutBookingWorkerSpec.swift
- KarhooUISDKTests/TestCases/Screens/Rides/KarhooRideDetailsPresenterSpec.swift
- KarhooUISDKTests/TestCases/Screens/SideMenu/SideMenuContentPresenterTest.swift
- Package.swift
- Podfile
- Podfile.lock
[MOB-4794](https://karhoo.atlassian.net/browse/MOB-4794)
[MOB-4794]: https://karhoo.atlassian.net/browse/MOB-4794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4794 remove karhoo user

- Package.swift
- Podfile
[MOB-4794](https://karhoo.atlassian.net/browse/MOB-4794)
[MOB-4794]: https://karhoo.atlassian.net/browse/MOB-4794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4794 revert nsdk to master

- .swiftlint.yml
[MOB-3880](https://karhoo.atlassian.net/browse/MOB-3880)
[MOB-3880]: https://karhoo.atlassian.net/browse/MOB-3880?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-3880 add more lint rules

- ClientSPM/ClientSPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- ClientSPM/ClientSPM/ClientSPMApp.swift
[MOB-4794](https://karhoo.atlassian.net/browse/MOB-4794)
[MOB-4794]: https://karhoo.atlassian.net/browse/MOB-4794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4794 cleanup deprecated auth method mention in ClientSPM

- ClientSPM/ClientSPM/ClientSPMApp.swift
[MOB-0000](https://karhoo.atlassian.net/browse/MOB-0000)
> MOB-0000 test

- Package.swift
[MOB-4865](https://karhoo.atlassian.net/browse/MOB-4865)
[MOB-4865]: https://karhoo.atlassian.net/browse/MOB-4865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4865 fix country json inclusion in bundle for SPM

- KarhooUISDK/FeatureFlags/FeatureFlagsUpdater.swift
- KarhooUISDK/FeatureFlags/feature_flag.json
[MOB-4801](https://karhoo.atlassian.net/browse/MOB-4801)
[MOB-4801]: https://karhoo.atlassian.net/browse/MOB-4801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4801 deactivate adyen

- BraintreePSP/BraintreePaymentScreensBuilder.swift
[MOB-4890](https://karhoo.atlassian.net/browse/MOB-4890)
[MOB-4890]: https://karhoo.atlassian.net/browse/MOB-4890?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4890 disable apple pay

- KarhooUISDK/Screens/QuoteList/KarhooQuoteListViewModel.swift
- Podfile
- Podfile.lock
[MOB-4891](https://karhoo.atlassian.net/browse/MOB-4891)
[MOB-4891]: https://karhoo.atlassian.net/browse/MOB-4891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4891 reduce number of calls to quotes api

- ClientSPM/ClientSPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/API/KarhooUISDKConfiguration.swift
- KarhooUISDK/Translations/Base.lproj/Localizable.strings
- KarhooUISDK/Translations/de.lproj/Localizable.strings
- KarhooUISDK/Translations/en.lproj/Localizable.strings
- KarhooUISDK/Translations/es.lproj/Localizable.strings
- KarhooUISDK/Translations/fr.lproj/Localizable.strings
- KarhooUISDK/Translations/id.lproj/Localizable.strings
- KarhooUISDK/Translations/it.lproj/Localizable.strings
- KarhooUISDK/Translations/ja.lproj/Localizable.strings
- KarhooUISDK/Translations/nl.lproj/Localizable.strings
- KarhooUISDK/Translations/pl.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-BR.lproj/Localizable.strings
- KarhooUISDK/Translations/pt-PT.lproj/Localizable.strings
- KarhooUISDK/Translations/ru.lproj/Localizable.strings
- KarhooUISDK/Translations/th.lproj/Localizable.strings
- KarhooUISDK/Translations/zh-Hans.lproj/Localizable.strings
- Package.resolved
- Package.swift
- Podfile
- Podfile.lock
- README.md
[MOB-4893](https://karhoo.atlassian.net/browse/MOB-4893)
[MOB-4893]: https://karhoo.atlassian.net/browse/MOB-4893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4893 release 1.13.2

- ClientSPM/ClientSPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- KarhooUISDK/API/KarhooUI.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingPresenter.swift
- KarhooUISDKUITests/SnapshotUtils.swift
- Package.resolved
- Package.swift
- Podfile
- Podfile.lock
[MOB-4767](https://karhoo.atlassian.net/browse/MOB-4767)
[MOB-4767]: https://karhoo.atlassian.net/browse/MOB-4767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4767 internal initial setup tweaks

- Client/ViewController.swift
[MOB-4902](https://karhoo.atlassian.net/browse/MOB-4902)
[MOB-4902]: https://karhoo.atlassian.net/browse/MOB-4902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4902 remove adyen options when opening the client app

- ClientSPM/ClientSPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- KarhooUISDK/Screens/QuoteList/KarhooQuoteListViewModel.swift
- KarhooUISDKTests/KarhooSDKService/Quote/MockQuoteService.swift
- KarhooUISDKUITests/SnapshotUtils.swift
- Package.swift
- Podfile
- Podfile.lock
[MOB-3694](https://karhoo.atlassian.net/browse/MOB-3694)
[MOB-3694]: https://karhoo.atlassian.net/browse/MOB-3694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-3694 send locale to quote list request

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- Package.resolved
- Package.swift
- Podfile
- Podfile.lock
- README.md
[MOB-4909](https://karhoo.atlassian.net/browse/MOB-4909)
[MOB-4909]: https://karhoo.atlassian.net/browse/MOB-4909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4909 bump version to 1.13.3

- CODEOWNERS
https://karhoo.atlassian.net/browse/INF-3497
Add Codeowners rule to to secure jr check
Codeowners file
- [ x] New feature 
> INF-3497 Add Codeowners rule to to secure jr check

- Client/ViewController.swift
- ClientSPM/ClientSPM.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- KarhooUISDK.xcodeproj/project.pbxproj
- KarhooUISDK/API/KarhooComponents.swift
- KarhooUISDK/Builders/BookingScreenBuilder.swift
- KarhooUISDK/CommonUI/MapMVP/AppleMapKit/KarhooMKMapView.swift
- KarhooUISDK/CommonUI/MapMVP/AppleMapKit/MapAnnotationViewModel.swift
- KarhooUISDK/CommonUI/MapMVP/MapMVP.swift
- KarhooUISDK/Controllers/NavigationController.swift
- KarhooUISDK/Models/JourneyInfo.swift
- KarhooUISDK/Routing/MainFlowCoordinator.swift
- KarhooUISDK/Screens/BookingMapScreen/BookingMapScreen+MVP.swift
- KarhooUISDK/Screens/BookingMapScreen/BookingMapScreenPresenter.swift
- KarhooUISDK/Screens/BookingMapScreen/BookingMapViewController.swift
- KarhooUISDK/Screens/BookingScreen/KarhooBookingViewController.swift
- KarhooUISDK/Screens/CheckoutScreen/Checkout/Checkout+MVVMC.swift
- KarhooUISDK/Screens/TripScreen/Map/KarhooTripMapPresenter.swift
- KarhooUISDK/UIComponents/AddressBarMVP/AddressBarMVP.swift
- KarhooUISDK/UIComponents/AddressBarMVP/KarhooAddressBarView.swift
- KarhooUISDKTestUtils/Mocks/Common/MockAddressBarView.swift
- KarhooUISDKTestUtils/Mocks/Common/MockKarhooMapView.swift
- Podfile.lock
[MOB-4913](https://karhoo.atlassian.net/browse/MOB-4913)
[MOB-4913]: https://karhoo.atlassian.net/browse/MOB-4913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4913 expose map component

- Client/KarhooConfig.swift
- Client/ViewController.swift
- KarhooUISDK/API/KarhooUISDKConfiguration.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/Filters/QuoteListFilter.swift
- KarhooUISDK/Screens/QuoteList/QuoteListFilters/FiltersViews/FilterViewBuilder.swift
[MOB-4919](https://karhoo.atlassian.net/browse/MOB-4919)
[MOB-4919]: https://karhoo.atlassian.net/browse/MOB-4919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4919 exclude filter categories

- Client/KarhooConfig.swift
- Client/ViewController.swift
- KarhooUISDK/API/KarhooUISDKConfiguration.swift
- KarhooUISDK/CommonUI/Views/StackButtonView/KarhooStackButtonView.swift
- KarhooUISDK/Screens/Rides/RideDetails/StackButton/RideDetailsStackButtonPresenter.swift
[MOB-4921](https://karhoo.atlassian.net/browse/MOB-4921)
[MOB-4921]: https://karhoo.atlassian.net/browse/MOB-4921?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4921 disable call driver in follow driver and ride details screens

- KarhooUISDK.podspec
- KarhooUISDK.xcodeproj/project.pbxproj
- README.md
[MOB-4926](https://karhoo.atlassian.net/browse/MOB-4926)
[MOB-4926]: https://karhoo.atlassian.net/browse/MOB-4926?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4926 bump version to 1.13.4

- KarhooUISDK/Translations/de.lproj/Localizable.strings
- Podfile.lock
[MOB-4931](https://karhoo.atlassian.net/browse/MOB-4931)
[MOB-4931]: https://karhoo.atlassian.net/browse/MOB-4931?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4931 update German translations for metered taxi price description

- KarhooUISDK/Workers/AddToCalendarWorker.swift
- Podfile.lock
[MOB-4925](https://karhoo.atlassian.net/browse/MOB-4925)
[MOB-4925]: https://karhoo.atlassian.net/browse/MOB-4925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> MOB-4925 add new calendar access method for iOS 17.0+
